// Reactor — CONTRACT.md §22, run against the committed §22.13 reference vectors.
//
// The vectors are generated by the AXIAM server's own sign path, so these are
// not "does my implementation agree with itself" tests: a byte out of place in
// the canonical form produces a MAC that differs from a number the server
// computed, and the test says so.
//
// THE THREE PLACES A §22 PORT ACTUALLY BREAKS, all covered below:
//
//  1. `hmac_signature` is serialized as **null** INSIDE the signed bytes, not
//     omitted as §8's own two message types omit it. A JSON library will drop or
//     reorder that null, which is why both canonical forms are built by hand.
//  2. `reason`, `patch` and `require_mfa` are OMITTED when absent or false. A
//     reply that serializes `"require_mfa": false` produces different bytes and
//     therefore a different MAC — reproduce the omission rule, not the values.
//  3. Freshness is two-sided. A future timestamp is not "extra fresh"; it is the
//     shape of a captured message held for later.

#include <cstdint>
#include <fstream>
#include <map>
#include <optional>
#include <string>
#include <vector>

#include <json.hpp>

#include <openssl/hmac.h>
#include <iomanip>
#include <sstream>
#include <ctime>

#include "assert.hpp"
#include "axiam/errors.hpp"
#include "axiam/reactor.hpp"

namespace {

using json = nlohmann::json;

const json& vectors() {
    static const json kVectors = [] {
        std::ifstream in(AXIAM_REACTOR_VECTORS);
        AXIAM_REQUIRE(in.good());
        json parsed;
        in >> parsed;
        return parsed;
    }();
    return kVectors;
}

/// The tenant's derived AMQP subkey (§8.1) as RAW BYTES — the vectors publish it
/// in hex, and signing the hex string instead of the bytes is a MAC that will
/// never verify against anything the server produced.
axiam::Sensitive<std::string> signing_key() {
    const std::string hex = vectors()["hkdf"]["derived_subkey_hex"].get<std::string>();
    std::string bytes;
    bytes.reserve(hex.size() / 2);
    for (std::size_t i = 0; i + 1 < hex.size(); i += 2) {
        bytes.push_back(static_cast<char>(std::stoi(hex.substr(i, 2), nullptr, 16)));
    }
    return axiam::Sensitive<std::string>(bytes);
}

std::string tenant_id() { return vectors()["tenant_id"].get<std::string>(); }
std::string correlation_id() { return vectors()["expected_correlation_id"].get<std::string>(); }

/// The instant the vectors were signed, so freshness passes deterministically.
/// A suite that used the real clock would start failing on a date nobody chose.
std::int64_t verified_at() {
    std::tm tm{};
    ::strptime(vectors()["verified_at"].get<std::string>().c_str(), "%Y-%m-%dT%H:%M:%SZ", &tm);
    return static_cast<std::int64_t>(::timegm(&tm));
}

/// The wire body: the committed message, dumped compactly. nlohmann sorts object
/// keys, which is exactly what the server's BTreeMap does — the ONE place a
/// library dump is safe here, and only because the canonical form is rebuilt by
/// hand from it afterwards.
std::string wire_body(const json& vector) { return vector["message"].dump(); }

/// Sign an event body the way the SERVER does, so a test can build a validly
/// signed variant and isolate one defect at a time.
///
/// Written out longhand rather than borrowed from the SDK on purpose: a test
/// that signed through the code under test could not tell a canonical-form bug
/// from agreement with itself. What proves this signer right is that the
/// committed vectors reproduce under it — asserted below.
std::string sign_event(const json& message) {
    auto quoted = [](const std::string& v) { return json(v).dump(); };
    const std::string canonical =
        std::string("{") + "\"tenant_id\":" + quoted(message.at("tenant_id").get<std::string>()) +
        ",\"event\":" + quoted(message.at("event").get<std::string>()) +
        ",\"correlation_id\":" + quoted(message.at("correlation_id").get<std::string>()) +
        ",\"payload\":" + message.at("payload").dump() +
        ",\"timeout_ms\":" + std::to_string(message.at("timeout_ms").get<std::int64_t>()) +
        ",\"key_version\":" + std::to_string(message.at("key_version").get<std::int64_t>()) +
        ",\"nonce\":" + quoted(message.at("nonce").get<std::string>()) +
        ",\"issued_at\":" + quoted(message.at("issued_at").get<std::string>()) +
        ",\"hmac_signature\":null}";

    const std::string key = axiam::detail::reveal(signing_key());
    unsigned char mac[EVP_MAX_MD_SIZE] = {0};
    unsigned int len = 0;
    ::HMAC(EVP_sha256(), key.data(), static_cast<int>(key.size()),
           reinterpret_cast<const unsigned char*>(canonical.data()), canonical.size(), mac, &len);
    std::ostringstream hex;
    hex << std::hex << std::setfill('0');
    for (unsigned int i = 0; i < len; ++i) hex << std::setw(2) << static_cast<int>(mac[i]);

    json signed_message = message;
    signed_message["hmac_signature"] = hex.str();
    return signed_message.dump();
}

/// The committed event vector, re-stamped to `issued_at` and re-signed.
std::string event_at(const std::string& issued_at, const std::string& nonce = "") {
    json message = vectors()["server_to_reactor"]["login_post_auth"]["message"];
    message["issued_at"] = issued_at;
    if (!nonce.empty()) message["nonce"] = nonce;
    return sign_event(message);
}

std::string rfc3339_now(std::int64_t offset_seconds = 0) {
    const std::time_t t = std::time(nullptr) + offset_seconds;
    std::tm tm{};
    ::gmtime_r(&t, &tm);
    char buf[32];
    std::strftime(buf, sizeof(buf), "%Y-%m-%dT%H:%M:%SZ", &tm);
    return buf;
}

axiam::ReactorDecision decision_from(const json& outcome) {
    const std::string kind = outcome["kind"].get<std::string>();
    if (kind == "deny") {
        return axiam::ReactorDecision::deny(outcome.value("reason", std::string{}));
    }
    if (kind == "mutate") {
        std::map<std::string, std::string> patch;
        for (auto it = outcome["patch"].begin(); it != outcome["patch"].end(); ++it) {
            patch[it.key()] = it.value().get<std::string>();
        }
        return axiam::ReactorDecision::mutate(std::move(patch));
    }
    // The vectors spell the step-up answer as its own `kind`, which is exactly
    // the shape §22.4 says it is NOT: `require_mfa` rides on `allow` rather than
    // being a fourth decision value, and the canonical bytes show that.
    if (kind == "require_mfa") return axiam::ReactorDecision::allow_with_step_up();
    return axiam::ReactorDecision::allow();
}

/// A transport that hands over a fixed script and records what was published.
/// §22.13's runtime assertions are about COUNTS — zero published messages, never
/// an `allow` — so recording is the whole job.
class ScriptedTransport final : public axiam::ReactorTransport {
public:
    explicit ScriptedTransport(std::vector<axiam::ReactorDelivery> script)
        : script_(std::move(script)) {}

    std::optional<axiam::ReactorDelivery> next_delivery() override {
        if (at_ >= script_.size()) return std::nullopt;
        return script_[at_++];
    }
    void publish_reply(const std::string& destination, const std::string& correlation_id,
                       const std::string& body) override {
        published.push_back({destination, correlation_id, body});
    }

    struct Published {
        std::string destination;
        std::string correlation_id;
        std::string body;
    };
    std::vector<Published> published;

private:
    std::vector<axiam::ReactorDelivery> script_;
    std::size_t at_ = 0;
};

axiam::ReactorDelivery delivery_of(const json& vector) {
    axiam::ReactorDelivery d;
    d.body = wire_body(vector);
    d.reply_to = "axiam.reactor.replies";
    d.correlation_id = vector["message"]["correlation_id"].get<std::string>();
    return d;
}

/// A config pinned to the vectors' own clock and nonce, so the sign direction is
/// reproducible byte-for-byte. Never how production is configured.
axiam::ReactorConfig pinned_config(const std::string& nonce) {
    axiam::ReactorConfig config;
    config.tenant_id = tenant_id();
    config.reactor_id = vectors()["reactor_id"].get<std::string>();
    config.signing_key = signing_key();
    config.clock = [] { return verified_at(); };
    config.nonce_source = [nonce] { return nonce; };
    return config;
}

bool contains(const std::vector<std::string>& haystack, const std::string& needle) {
    for (const auto& s : haystack) {
        if (s == needle) return true;
    }
    return false;
}

}  // namespace

// ---------------------------------------------------------------------------
// §22.13 — sign direction
// ---------------------------------------------------------------------------

AXIAM_TEST("reactor: every committed reply vector reproduces its canonical bytes and MAC") {
    const json& replies = vectors()["reactor_to_server"];
    for (auto it = replies.begin(); it != replies.end(); ++it) {
        const json& vector = it.value();
        const auto decision = decision_from(vector["expected_outcome"]);
        const std::string event = vector["message"]["event"].get<std::string>();
        const std::string nonce = vector["message"]["nonce"].get<std::string>();
        const std::string issued_at = vector["message"]["issued_at"].get<std::string>();

        const std::string canonical = axiam::reactor_canonical_reply(
            correlation_id(), tenant_id(), event, decision, nonce, issued_at);
        AXIAM_REQUIRE(canonical == vector["canonical_signed_json"].get<std::string>());

        const std::string wire = axiam::reactor_build_reply(
            signing_key(), correlation_id(), tenant_id(), event, decision, nonce, issued_at);
        const json parsed = json::parse(wire);
        AXIAM_REQUIRE(parsed["hmac_signature"].get<std::string>() ==
                      vector["hmac_signature_hex"].get<std::string>());
    }
}

AXIAM_TEST("reactor: require_mfa is OMITTED when false, not serialized as false") {
    // The omission changes the canonical bytes and therefore the MAC. An
    // implementation that reproduces the values but not the omission rule passes
    // every "is the field right" assertion and fails every real reply.
    const std::string canonical = axiam::reactor_canonical_reply(
        correlation_id(), tenant_id(), axiam::kReactorEventLoginPostAuth,
        axiam::ReactorDecision::allow(), "n", "2026-07-10T12:00:00Z");
    AXIAM_REQUIRE(canonical.find("require_mfa") == std::string::npos);

    const std::string with_step_up = axiam::reactor_canonical_reply(
        correlation_id(), tenant_id(), axiam::kReactorEventLoginPostAuth,
        axiam::ReactorDecision::allow_with_step_up(), "n", "2026-07-10T12:00:00Z");
    AXIAM_REQUIRE(with_step_up.find("\"require_mfa\":true") != std::string::npos);
}

AXIAM_TEST("reactor: reason and patch are OMITTED when absent") {
    const std::string allow = axiam::reactor_canonical_reply(
        correlation_id(), tenant_id(), axiam::kReactorEventTokenPreIssue,
        axiam::ReactorDecision::allow(), "n", "2026-07-10T12:00:00Z");
    AXIAM_REQUIRE(allow.find("reason") == std::string::npos);
    AXIAM_REQUIRE(allow.find("patch") == std::string::npos);

    // A deny with no reason still denies; the server substitutes "denied by
    // reactor". An empty reason is omitted, not sent as "".
    const std::string bare_deny = axiam::reactor_canonical_reply(
        correlation_id(), tenant_id(), axiam::kReactorEventLoginPostAuth,
        axiam::ReactorDecision::deny(""), "n", "2026-07-10T12:00:00Z");
    AXIAM_REQUIRE(bare_deny.find("reason") == std::string::npos);
    AXIAM_REQUIRE(bare_deny.find("\"decision\":\"deny\"") != std::string::npos);
}

AXIAM_TEST("reactor: the nonce is inside the signed bytes") {
    // Two replies differing only in `nonce` carry different MACs — the
    // `nonce_binding` vector pair, checked against the server's own numbers.
    const json& binding = vectors()["nonce_binding"];
    // The pair is the `allow` reply vector with only its nonce changed, so the
    // first MAC must equal that vector's own committed signature.
    const auto decision = axiam::ReactorDecision::allow();
    const std::string a = axiam::reactor_build_reply(
        signing_key(), correlation_id(), tenant_id(), axiam::kReactorEventLoginPostAuth, decision,
        binding["nonce_a"].get<std::string>(), "2026-07-10T12:00:00Z");
    const std::string b = axiam::reactor_build_reply(
        signing_key(), correlation_id(), tenant_id(), axiam::kReactorEventLoginPostAuth, decision,
        binding["nonce_b"].get<std::string>(), "2026-07-10T12:00:00Z");

    AXIAM_REQUIRE(json::parse(a)["hmac_signature"].get<std::string>() ==
                  binding["hmac_a_hex"].get<std::string>());
    AXIAM_REQUIRE(json::parse(b)["hmac_signature"].get<std::string>() ==
                  binding["hmac_b_hex"].get<std::string>());
    AXIAM_REQUIRE(binding["hmac_a_hex"] != binding["hmac_b_hex"]);
}

AXIAM_TEST("reactor: a mutate answer never becomes allow + patch") {
    const std::string canonical = axiam::reactor_canonical_reply(
        correlation_id(), tenant_id(), axiam::kReactorEventTokenPreIssue,
        axiam::ReactorDecision::mutate({{"ext.department", "eng"}}), "n",
        "2026-07-10T12:00:00Z");
    AXIAM_REQUIRE(canonical.find("\"decision\":\"mutate\"") != std::string::npos);
    AXIAM_REQUIRE(canonical.find("\"decision\":\"allow\"") == std::string::npos);
}

AXIAM_TEST("reactor: a forbidden patch key is sent UNFILTERED") {
    // §22.4 rule 1 / §22.10 rule 3. One forbidden key rejects the WHOLE patch
    // server-side, including the fields that would have been fine — and dropping
    // the offender to rescue the rest would leave the author believing a field
    // was set when it was dropped.
    const auto decision =
        axiam::ReactorDecision::mutate({{"ext.department", "eng"}, {"sub", "attacker"}});
    const std::string canonical = axiam::reactor_canonical_reply(
        correlation_id(), tenant_id(), axiam::kReactorEventTokenPreIssue, decision, "n",
        "2026-07-10T12:00:00Z");
    AXIAM_REQUIRE(canonical.find("\"sub\":\"attacker\"") != std::string::npos);
    // And the SDK knows perfectly well it is forbidden — it just does not act on
    // that knowledge when building the reply.
    AXIAM_REQUIRE_FALSE(
        axiam::reactor_patch_field_allowed(axiam::kReactorEventTokenPreIssue, "sub"));
}

AXIAM_TEST("reactor: require_mfa on any other event is refused client-side") {
    // Refused rather than corrected: the result is NO REPLY, and the
    // registration's failure_policy decides.
    AXIAM_REQUIRE_THROWS_AS(
        axiam::reactor_build_reply(signing_key(), correlation_id(), tenant_id(),
                                   axiam::kReactorEventTokenPreIssue,
                                   axiam::ReactorDecision::allow_with_step_up(), "n",
                                   "2026-07-10T12:00:00Z"),
        axiam::AuthError);
}

AXIAM_TEST("reactor: an empty mutate is refused client-side") {
    AXIAM_REQUIRE_THROWS_AS(
        axiam::reactor_build_reply(signing_key(), correlation_id(), tenant_id(),
                                   axiam::kReactorEventTokenPreIssue,
                                   axiam::ReactorDecision::mutate({}), "n",
                                   "2026-07-10T12:00:00Z"),
        axiam::AuthError);
}

// ---------------------------------------------------------------------------
// §22.13 — verify direction
// ---------------------------------------------------------------------------

AXIAM_TEST("reactor: every committed event vector verifies under the derived subkey") {
    const json& events = vectors()["server_to_reactor"];
    for (auto it = events.begin(); it != events.end(); ++it) {
        const auto v = axiam::reactor_verify_event(signing_key(), wire_body(it.value()),
                                                   tenant_id(), verified_at(), nullptr);
        AXIAM_REQUIRE(v.ok);
        AXIAM_REQUIRE(v.event.event == it.value()["message"]["event"].get<std::string>());
        AXIAM_REQUIRE(v.event.correlation_id == correlation_id());
    }
}

AXIAM_TEST("reactor: an event fails under any other key") {
    const json& events = vectors()["server_to_reactor"];
    const auto other = axiam::Sensitive<std::string>(std::string(32, '\x01'));
    for (auto it = events.begin(); it != events.end(); ++it) {
        const auto v = axiam::reactor_verify_event(other, wire_body(it.value()), tenant_id(),
                                                   verified_at(), nullptr);
        AXIAM_REQUIRE_FALSE(v.ok);
        AXIAM_REQUIRE(v.refusal == axiam::ReactorRefusal::kBadSignature);
    }
}

AXIAM_TEST("reactor: tampering with any signed field invalidates the event") {
    const json& vector = vectors()["server_to_reactor"]["login_post_auth"];
    for (const char* field : {"payload", "timeout_ms", "tenant_id", "nonce"}) {
        json tampered = vector["message"];
        if (std::string(field) == "timeout_ms") {
            tampered[field] = tampered[field].get<std::int64_t>() + 1;
        } else if (std::string(field) == "payload") {
            tampered[field]["sub"] = "mallory";
        } else {
            tampered[field] = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa";
        }
        const auto v = axiam::reactor_verify_event(signing_key(), tampered.dump(), tenant_id(),
                                                   verified_at(), nullptr);
        AXIAM_REQUIRE_FALSE(v.ok);
        AXIAM_REQUIRE(v.refusal == axiam::ReactorRefusal::kBadSignature);
    }
}

AXIAM_TEST("reactor: key_version below 2 is refused before the signature is computed") {
    json downgraded = vectors()["server_to_reactor"]["login_post_auth"]["message"];
    downgraded["key_version"] = 1;
    const auto v = axiam::reactor_verify_event(signing_key(), downgraded.dump(), tenant_id(),
                                               verified_at(), nullptr);
    AXIAM_REQUIRE_FALSE(v.ok);
    // Not kBadSignature: the version check comes first, and reporting it as a
    // signature failure would send an operator looking at the wrong key.
    AXIAM_REQUIRE(v.refusal == axiam::ReactorRefusal::kKeyVersionTooOld);
}

AXIAM_TEST("reactor: freshness is refused in BOTH directions") {
    const json& vector = vectors()["server_to_reactor"]["login_post_auth"];
    const std::int64_t skew = vectors()["freshness_skew_secs"].get<std::int64_t>();

    const auto stale = axiam::reactor_verify_event(signing_key(), wire_body(vector), tenant_id(),
                                                   verified_at() + skew + 1, nullptr);
    AXIAM_REQUIRE_FALSE(stale.ok);
    AXIAM_REQUIRE(stale.refusal == axiam::ReactorRefusal::kStale);

    // A future timestamp is not "extra fresh" — it is the shape of a captured
    // message held for later.
    const auto future = axiam::reactor_verify_event(signing_key(), wire_body(vector), tenant_id(),
                                                    verified_at() - skew - 1, nullptr);
    AXIAM_REQUIRE_FALSE(future.ok);
    AXIAM_REQUIRE(future.refusal == axiam::ReactorRefusal::kStale);

    // And the boundary itself is inside the window.
    AXIAM_REQUIRE(axiam::reactor_verify_event(signing_key(), wire_body(vector), tenant_id(),
                                              verified_at() + skew, nullptr)
                      .ok);
}

AXIAM_TEST("reactor: a repeated nonce is refused as a replay") {
    const json& vector = vectors()["server_to_reactor"]["login_post_auth"];
    std::map<std::string, std::int64_t> seen;

    AXIAM_REQUIRE(axiam::reactor_verify_event(signing_key(), wire_body(vector), tenant_id(),
                                              verified_at(), &seen)
                      .ok);
    const auto again = axiam::reactor_verify_event(signing_key(), wire_body(vector), tenant_id(),
                                                   verified_at(), &seen);
    AXIAM_REQUIRE_FALSE(again.ok);
    AXIAM_REQUIRE(again.refusal == axiam::ReactorRefusal::kReplay);
}

AXIAM_TEST("reactor: an event for another tenant is refused after the MAC") {
    const json& vector = vectors()["server_to_reactor"]["login_post_auth"];
    const auto v = axiam::reactor_verify_event(signing_key(), wire_body(vector),
                                               "99999999-9999-9999-9999-999999999999",
                                               verified_at(), nullptr);
    AXIAM_REQUIRE_FALSE(v.ok);
    AXIAM_REQUIRE(v.refusal == axiam::ReactorRefusal::kTenantMismatch);
}

AXIAM_TEST("reactor: a body that is not JSON is refused as malformed") {
    const auto v = axiam::reactor_verify_event(signing_key(), "<html>", tenant_id(),
                                               verified_at(), nullptr);
    AXIAM_REQUIRE_FALSE(v.ok);
    AXIAM_REQUIRE(v.refusal == axiam::ReactorRefusal::kMalformed);
}

// ---------------------------------------------------------------------------
// §22.13 — replay and correlation binding
// ---------------------------------------------------------------------------

AXIAM_TEST("reactor: the correlation_replay vector is refused against another correlation_id") {
    // The accepted reply verbatim — valid signature, inside the freshness window
    // — presented against a different in-flight event. The correlation_id is
    // inside the signed bytes, so re-signing for the other event is what an
    // attacker cannot do; this asserts the SDK's own reply for that event does
    // not collide with the replayed one.
    const json& replay = vectors()["rejected_replies"]["correlation_replay"];
    const std::string other = replay["verify_against_correlation_id"].get<std::string>();
    const auto decision = axiam::ReactorDecision::allow();
    const std::string event = replay["message"]["event"].get<std::string>();

    const std::string for_other = axiam::reactor_build_reply(
        signing_key(), other, tenant_id(), event, decision,
        replay["message"]["nonce"].get<std::string>(),
        replay["message"]["issued_at"].get<std::string>());
    AXIAM_REQUIRE(json::parse(for_other)["hmac_signature"].get<std::string>() !=
                  replay["hmac_signature_hex"].get<std::string>());
}

// ---------------------------------------------------------------------------
// §22.5 — the registry and its allow-lists
// ---------------------------------------------------------------------------

AXIAM_TEST("reactor: token.pre_issue admits the ext namespace and nothing else") {
    using axiam::reactor_patch_field_allowed;
    const char* e = axiam::kReactorEventTokenPreIssue;
    AXIAM_REQUIRE(reactor_patch_field_allowed(e, "ext.department"));
    AXIAM_REQUIRE(reactor_patch_field_allowed(e, "ext.a.b.c"));
    // `ext.` names the namespace, not a claim.
    AXIAM_REQUIRE_FALSE(reactor_patch_field_allowed(e, "ext."));
    AXIAM_REQUIRE_FALSE(reactor_patch_field_allowed(e, "ext"));
    // A prefix match on the string is not a match on the namespace.
    AXIAM_REQUIRE_FALSE(reactor_patch_field_allowed(e, "extra"));
    AXIAM_REQUIRE_FALSE(reactor_patch_field_allowed(e, "external_id"));
    AXIAM_REQUIRE_FALSE(reactor_patch_field_allowed(e, "evil.ext.department"));
    // Every standard claim, because none of them begins with `ext.` — which is
    // the whole design: a hook that could rewrite `sub` could mint a token for
    // anyone.
    for (const char* claim : {"sub", "aud", "exp", "iat", "iss", "scope", "tenant_id"}) {
        AXIAM_REQUIRE_FALSE(reactor_patch_field_allowed(e, claim));
    }
}

AXIAM_TEST("reactor: user.pre_create admits its named fields and its metadata namespace") {
    using axiam::reactor_patch_field_allowed;
    const char* e = axiam::kReactorEventUserPreCreate;
    AXIAM_REQUIRE(reactor_patch_field_allowed(e, "email"));
    AXIAM_REQUIRE(reactor_patch_field_allowed(e, "username"));
    AXIAM_REQUIRE(reactor_patch_field_allowed(e, "metadata.source"));
    AXIAM_REQUIRE_FALSE(reactor_patch_field_allowed(e, "metadata"));  // bare namespace
    AXIAM_REQUIRE_FALSE(reactor_patch_field_allowed(e, "password"));
    AXIAM_REQUIRE_FALSE(reactor_patch_field_allowed(e, "tenant_id"));
    AXIAM_REQUIRE_FALSE(reactor_patch_field_allowed(e, "roles"));
}

AXIAM_TEST("reactor: the veto-only events accept no patch field at all") {
    for (const char* e : {axiam::kReactorEventLoginPostAuth, axiam::kReactorEventGrantPreAssign}) {
        for (const char* f : {"email", "ext.department", "metadata.source", "anything"}) {
            AXIAM_REQUIRE_FALSE(axiam::reactor_patch_field_allowed(e, f));
        }
    }
}

AXIAM_TEST("reactor: the hot-path operations are absent from every exposed constant") {
    // §22.7 is a normative MUST NOT, and §22.13 says to assert on the list rather
    // than on a comment. A reactor round trip is milliseconds; the check path's
    // budget is microseconds.
    const auto& names = axiam::reactor_event_names();
    AXIAM_REQUIRE_FALSE(contains(names, "authz.check"));
    AXIAM_REQUIRE_FALSE(contains(names, "authz.check_batch"));
    AXIAM_REQUIRE_FALSE(contains(names, "token.introspect"));
    AXIAM_REQUIRE(names.size() == 5);
}

AXIAM_TEST("reactor: the strictest default wins, in either array order") {
    using axiam::reactor_default_failure_policy;
    AXIAM_REQUIRE(reactor_default_failure_policy({axiam::kReactorEventTokenPreIssue}) ==
                  "fail_open");
    AXIAM_REQUIRE(reactor_default_failure_policy({axiam::kReactorEventLoginPostAuth}) ==
                  "fail_closed");
    // Both orders, because reducing this to "take the first event's default"
    // would let the order of a JSON array decide whether an unreachable fraud
    // check passes.
    AXIAM_REQUIRE(reactor_default_failure_policy(
                      {axiam::kReactorEventTokenPreIssue, axiam::kReactorEventLoginPostAuth}) ==
                  "fail_closed");
    AXIAM_REQUIRE(reactor_default_failure_policy(
                      {axiam::kReactorEventLoginPostAuth, axiam::kReactorEventTokenPreIssue}) ==
                  "fail_closed");
    // An empty registration is not "nothing to fail at".
    AXIAM_REQUIRE(reactor_default_failure_policy({}) == "fail_closed");
}

AXIAM_TEST("reactor: the topology names match the vectors, and rendering is not declaring") {
    const json& topology = vectors()["topology"];
    AXIAM_REQUIRE(axiam::reactor_queue_name(tenant_id(),
                                            vectors()["reactor_id"].get<std::string>()) ==
                  topology["queue"].get<std::string>());
    AXIAM_REQUIRE(axiam::reactor_routing_key(tenant_id(), axiam::kReactorEventLoginPostAuth) ==
                  topology["routing_key_login_post_auth"].get<std::string>());
}

// ---------------------------------------------------------------------------
// §22.10 — the runtime
// ---------------------------------------------------------------------------

AXIAM_TEST("reactor: the runtime verifies, dispatches and publishes a signed reply") {
    const json& vector = vectors()["server_to_reactor"]["login_post_auth"];
    ScriptedTransport transport({delivery_of(vector)});

    std::string seen_event;
    axiam::reactor_serve(pinned_config("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"), transport,
                         [&seen_event](const axiam::ReactorEvent& e) -> axiam::ReactorAnswer {
                             seen_event = e.event;
                             return axiam::ReactorDecision::allow();
                         });

    AXIAM_REQUIRE(seen_event == "login.post_auth");
    AXIAM_REQUIRE(transport.published.size() == 1);
    AXIAM_REQUIRE(transport.published[0].correlation_id == correlation_id());
    const json reply = json::parse(transport.published[0].body);
    AXIAM_REQUIRE(reply["decision"] == "allow");
    AXIAM_REQUIRE(reply["key_version"] == 2);
    AXIAM_REQUIRE(reply["hmac_signature"].is_string());
}

AXIAM_TEST("reactor: a handler that throws produces NO reply") {
    // §22.10 rule 2, asserted as a COUNT rather than as an absent `allow`: a
    // runtime that answered on behalf of a handler that crashed would have
    // overridden the operator's fail_closed setting from inside the library.
    const json& vector = vectors()["server_to_reactor"]["login_post_auth"];
    ScriptedTransport transport({delivery_of(vector)});

    axiam::reactor_serve(pinned_config("n"), transport,
                         [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                             throw std::runtime_error("handler blew up");
                         });
    AXIAM_REQUIRE(transport.published.empty());
}

AXIAM_TEST("reactor: an unverifiable delivery produces NO reply") {
    json tampered = vectors()["server_to_reactor"]["login_post_auth"]["message"];
    tampered["payload"]["sub"] = "mallory";
    axiam::ReactorDelivery d;
    d.body = tampered.dump();
    d.reply_to = "axiam.reactor.replies";
    ScriptedTransport transport({d});

    bool handler_ran = false;
    axiam::reactor_serve(pinned_config("n"), transport,
                         [&handler_ran](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                             handler_ran = true;
                             return axiam::ReactorDecision::allow();
                         });
    // And the handler never saw it: a runtime that hands unverified bytes to user
    // code has already lost, because the handler will act on them.
    AXIAM_REQUIRE_FALSE(handler_ran);
    AXIAM_REQUIRE(transport.published.empty());
}

AXIAM_TEST("reactor: an abstaining handler produces NO reply") {
    const json& vector = vectors()["server_to_reactor"]["login_post_auth"];
    ScriptedTransport transport({delivery_of(vector)});

    axiam::reactor_serve(pinned_config("n"), transport,
                         [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                             return std::nullopt;
                         });
    AXIAM_REQUIRE(transport.published.empty());
}

AXIAM_TEST("reactor: the runtime keeps ONE nonce seen-set for its whole lifetime") {
    // Building a fresh set per delivery defeats replay dedup entirely, and the
    // only way to see the difference is to feed the same delivery twice.
    const json& vector = vectors()["server_to_reactor"]["login_post_auth"];
    ScriptedTransport transport({delivery_of(vector), delivery_of(vector)});

    int dispatches = 0;
    axiam::reactor_serve(pinned_config("n"), transport,
                         [&dispatches](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                             ++dispatches;
                             return axiam::ReactorDecision::allow();
                         });
    AXIAM_REQUIRE(dispatches == 1);
    AXIAM_REQUIRE(transport.published.size() == 1);
}

AXIAM_TEST("reactor: the runtime publishes to the delivery's reply_to") {
    const json& vector = vectors()["server_to_reactor"]["login_post_auth"];
    auto d = delivery_of(vector);
    d.reply_to = "amq.rabbitmq.reply-to.abc";
    ScriptedTransport transport({d});

    axiam::reactor_serve(pinned_config("n"), transport,
                         [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                             return axiam::ReactorDecision::allow();
                         });
    AXIAM_REQUIRE(transport.published.size() == 1);
    AXIAM_REQUIRE(transport.published[0].destination == "amq.rabbitmq.reply-to.abc");
}

AXIAM_TEST("reactor: a reply the builder refuses produces NO reply") {
    // require_mfa on token.pre_issue. The runtime's own error, and rule 2 applies
    // to it exactly as to a handler that threw.
    const json& vector = vectors()["server_to_reactor"]["token_pre_issue"];
    ScriptedTransport transport({delivery_of(vector)});

    axiam::reactor_serve(pinned_config("n"), transport,
                         [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                             return axiam::ReactorDecision::allow_with_step_up();
                         });
    AXIAM_REQUIRE(transport.published.empty());
}

AXIAM_TEST("reactor: the signing key never appears in a published reply") {
    const json& vector = vectors()["server_to_reactor"]["login_post_auth"];
    ScriptedTransport transport({delivery_of(vector)});

    axiam::reactor_serve(pinned_config("n"), transport,
                         [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                             return axiam::ReactorDecision::deny("nope");
                         });
    AXIAM_REQUIRE(transport.published.size() == 1);
    const std::string hex = vectors()["hkdf"]["derived_subkey_hex"].get<std::string>();
    AXIAM_REQUIRE(transport.published[0].body.find(hex) == std::string::npos);
    AXIAM_REQUIRE(transport.published[0].body.find(axiam::detail::reveal(signing_key())) ==
                  std::string::npos);
}

AXIAM_TEST("reactor: the signing key does not render") {
    // §22.12: the tenant AMQP signing key is a credential, exactly as §8's key
    // already is. It must not appear at any log level, nor in a reconnect
    // diagnostic.
    std::ostringstream os;
    os << signing_key();
    AXIAM_REQUIRE(os.str() == "[SENSITIVE]");
}

AXIAM_TEST("reactor: serve refuses a missing handler or tenant") {
    ScriptedTransport transport({});
    axiam::ReactorConfig config = pinned_config("n");
    AXIAM_REQUIRE_THROWS_AS(axiam::reactor_serve(config, transport, nullptr), axiam::AuthError);
    config.tenant_id.clear();
    AXIAM_REQUIRE_THROWS_AS(
        axiam::reactor_serve(config, transport,
                             [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                                 return axiam::ReactorDecision::allow();
                             }),
        axiam::AuthError);
}

// ---------------------------------------------------------------------------
// §22.14.1 — the binder, six tests for six rules
// ---------------------------------------------------------------------------

AXIAM_TEST("reactor router: two events reach their own handlers") {
    axiam::ReactorRouter router;
    std::string reached;
    router.on(axiam::kReactorEventLoginPostAuth,
              [&reached](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                  reached = "login";
                  return axiam::ReactorDecision::allow();
              })
        .on(axiam::kReactorEventTokenPreIssue,
            [&reached](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                reached = "token";
                return axiam::ReactorDecision::allow();
            });

    // The composed value IS what reactor_serve takes — a compile-time assertion
    // as much as a runtime one.
    const axiam::ReactorHandler handler = router.build();

    axiam::ReactorEvent login;
    login.event = axiam::kReactorEventLoginPostAuth;
    handler(login);
    AXIAM_REQUIRE(reached == "login");

    axiam::ReactorEvent token;
    token.event = axiam::kReactorEventTokenPreIssue;
    handler(token);
    AXIAM_REQUIRE(reached == "token");
}

AXIAM_TEST("reactor router: a name outside the registry is refused AT BIND TIME") {
    // Rule 2. Failing when the binding is written is the entire point: a typo
    // that survives to production is discovered as silence, and silence on a
    // fail_open event is indistinguishable from a healthy reactor with nothing
    // to say.
    axiam::ReactorRouter router;
    AXIAM_REQUIRE_THROWS_AS(
        router.on("login.postauth",
                  [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                      return axiam::ReactorDecision::allow();
                  }),
        axiam::AuthError);
}

AXIAM_TEST("reactor router: a hot-path operation is refused like any other unknown name") {
    // §22.7's three are in no registry row, so they fail rule 2 exactly as a typo
    // does — and the message names the registry rather than naming what is
    // absent from it. A separate hot-path list would be a constant naming them,
    // which §22.13's hot-path assertion forbids outright.
    axiam::ReactorRouter router;
    for (const char* hot : {"authz.check", "authz.check_batch", "token.introspect"}) {
        try {
            router.on(hot, [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                return axiam::ReactorDecision::allow();
            });
            AXIAM_REQUIRE(false);
        } catch (const axiam::AuthError& e) {
            const std::string msg = e.what();
            AXIAM_REQUIRE(msg.find("§22.5") != std::string::npos);
            AXIAM_REQUIRE(msg.find("hot") == std::string::npos);
        }
    }
}

AXIAM_TEST("reactor router: a second binding for one event is an error, not an overwrite") {
    // Rule 3. Which of two handlers runs is not something the author of either
    // can see from their own file.
    axiam::ReactorRouter router;
    router.on(axiam::kReactorEventLoginPostAuth,
              [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                  return axiam::ReactorDecision::allow();
              });
    AXIAM_REQUIRE_THROWS_AS(
        router.on(axiam::kReactorEventLoginPostAuth,
                  [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                      return axiam::ReactorDecision::deny("second");
                  }),
        axiam::AuthError);
}

AXIAM_TEST("reactor router: an unbound event ABSTAINS") {
    // Rule 4, and the reason this subsection exists. It is not answered `allow`,
    // and not answered `deny` either: the binder does not know what the
    // registration was for, and the operator's policy does.
    axiam::ReactorRouter router;
    router.on(axiam::kReactorEventLoginPostAuth,
              [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                  return axiam::ReactorDecision::allow();
              });
    const auto handler = router.build();

    axiam::ReactorEvent unbound;
    unbound.event = axiam::kReactorEventUserPreCreate;
    AXIAM_REQUIRE_FALSE(handler(unbound).has_value());

    // And through the runtime, where abstention means zero published messages.
    const json& vector = vectors()["server_to_reactor"]["token_pre_issue"];
    ScriptedTransport transport({delivery_of(vector)});
    axiam::reactor_serve(pinned_config("n"), transport, handler);
    AXIAM_REQUIRE(transport.published.empty());
}

AXIAM_TEST("reactor router: an explicit fallback is honoured and has no default") {
    axiam::ReactorRouter router;
    bool fell_back = false;
    router.fallback([&fell_back](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
        fell_back = true;
        return axiam::ReactorDecision::deny("unhandled by this reactor");
    });

    axiam::ReactorEvent unbound;
    unbound.event = axiam::kReactorEventUserPreCreate;
    const auto answer = router.build()(unbound);
    AXIAM_REQUIRE(fell_back);
    AXIAM_REQUIRE(answer.has_value());
    AXIAM_REQUIRE(answer->decision() == "deny");
}

AXIAM_TEST("reactor router: a handler's own failure propagates unchanged") {
    // Rule 5. §22.10 rule 2 puts the fail-closed obligation on the runtime, and a
    // binder that swallowed a failure before the runtime saw it would satisfy the
    // letter of that rule while defeating it.
    axiam::ReactorRouter router;
    router.on(axiam::kReactorEventLoginPostAuth,
              [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                  throw std::runtime_error("handler blew up");
              });
    const auto handler = router.build();

    axiam::ReactorEvent login;
    login.event = axiam::kReactorEventLoginPostAuth;
    AXIAM_REQUIRE_THROWS_AS(handler(login), std::runtime_error);
}

AXIAM_TEST("reactor router: a patch is not filtered on its way through") {
    // Rule 6. A binder sits between the handler and the runtime and is therefore
    // the newest place to be tempted into "helpfully" pruning a forbidden key.
    axiam::ReactorRouter router;
    router.on(axiam::kReactorEventTokenPreIssue,
              [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                  return axiam::ReactorDecision::mutate(
                      {{"ext.department", "eng"}, {"sub", "attacker"}});
              });

    axiam::ReactorEvent token;
    token.event = axiam::kReactorEventTokenPreIssue;
    const auto answer = router.build()(token);
    AXIAM_REQUIRE(answer.has_value());
    AXIAM_REQUIRE(answer->patch().size() == 2);
    AXIAM_REQUIRE(answer->patch().at("sub") == "attacker");
}

AXIAM_TEST("reactor router: it reports the events it bound") {
    axiam::ReactorRouter router;
    router.on(axiam::kReactorEventTokenPreIssue,
              [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                  return axiam::ReactorDecision::allow();
              })
        .on(axiam::kReactorEventLoginPostAuth,
            [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                return axiam::ReactorDecision::allow();
            });

    const auto bound = router.bound_events();
    AXIAM_REQUIRE(bound.size() == 2);
    // So the author can compute §22.8's default from the code that actually
    // handles the events rather than from a restatement of the registration.
    AXIAM_REQUIRE(axiam::reactor_default_failure_policy(bound) == "fail_closed");
}

// ---------------------------------------------------------------------------
// §8b rules 1–5 — the broker URL guard
// ---------------------------------------------------------------------------

AXIAM_TEST("amqps guard: an amqps URL is accepted and parsed") {
    const auto endpoint = axiam::amqps_endpoint("amqps://broker.internal:5671/prod");
    AXIAM_REQUIRE(endpoint.host == "broker.internal");
    AXIAM_REQUIRE(endpoint.port == 5671);
    AXIAM_REQUIRE(endpoint.virtual_host == "prod");
    AXIAM_REQUIRE(endpoint.url == "amqps://broker.internal:5671/prod");
}

AXIAM_TEST("amqps guard: the port defaults to the broker TLS port") {
    const auto endpoint = axiam::amqps_endpoint("amqps://broker.internal");
    AXIAM_REQUIRE(endpoint.port == 5671);
    AXIAM_REQUIRE(endpoint.virtual_host == "/");
}

AXIAM_TEST("amqps guard: plaintext is refused") {
    // Rule 1, and rule 5's posture: a failed amqps:// connection is an error to
    // surface, not a condition to work around — so there is no way to express a
    // plaintext fallback here at all.
    AXIAM_REQUIRE_THROWS_AS(axiam::amqps_endpoint("amqp://broker.internal:5672"),
                            axiam::AuthError);
}

AXIAM_TEST("amqps guard: there is NO loopback exception") {
    // §8b rule 8. §6's http://localhost dev carve-out does not extend to the
    // broker URL — they are different rules, and the server has no plaintext
    // listener for such an exception to reach.
    for (const char* url : {"amqp://localhost:5672", "amqp://127.0.0.1:5672", "amqp://[::1]:5672"}) {
        AXIAM_REQUIRE_THROWS_AS(axiam::amqps_endpoint(url), axiam::AuthError);
    }
    // And the TLS form of the same hosts is fine.
    AXIAM_REQUIRE_NOTHROW(axiam::amqps_endpoint("amqps://localhost:5671"));
}

AXIAM_TEST("amqps guard: every other scheme is refused too") {
    for (const char* url : {"http://broker", "https://broker", "amqps.evil://broker", "broker:5671",
                            "", "amqpss://broker"}) {
        AXIAM_REQUIRE_THROWS_AS(axiam::amqps_endpoint(url), axiam::AuthError);
    }
}

AXIAM_TEST("amqps guard: the scheme comparison is case-insensitive") {
    AXIAM_REQUIRE_NOTHROW(axiam::amqps_endpoint("AMQPS://broker.internal"));
}

AXIAM_TEST("amqps guard: half a client identity fails closed") {
    // Rule 3. Connecting without the mutual half would present no client identity
    // at all while the caller believes one was configured.
    AXIAM_REQUIRE_THROWS_AS(axiam::amqps_endpoint("amqps://broker", "", "CERT", ""),
                            axiam::AuthError);
    AXIAM_REQUIRE_THROWS_AS(axiam::amqps_endpoint("amqps://broker", "", "", "KEY"),
                            axiam::AuthError);
    AXIAM_REQUIRE_NOTHROW(axiam::amqps_endpoint("amqps://broker", "", "CERT", "KEY"));
}

AXIAM_TEST("amqps guard: a custom CA bundle is carried through") {
    // Rule 2 — the common case, and the reason nobody has a legitimate need for
    // rule 4 to be relaxed: an in-cluster broker's certificate is not issued by a
    // public CA.
    const auto endpoint = axiam::amqps_endpoint("amqps://broker", "CA-PEM");
    AXIAM_REQUIRE(endpoint.ca_pem == "CA-PEM");
}

AXIAM_TEST("amqps guard: userinfo is stripped from the host") {
    // Credentials belong to the connection, not to this check — and leaving them
    // in `host` would put them wherever host is logged.
    const auto endpoint = axiam::amqps_endpoint("amqps://user:pass@broker.internal:5671/v");
    AXIAM_REQUIRE(endpoint.host == "broker.internal");
    AXIAM_REQUIRE(endpoint.host.find("pass") == std::string::npos);
}

AXIAM_TEST("amqps guard: an IPv6 literal keeps its colons") {
    const auto endpoint = axiam::amqps_endpoint("amqps://[2001:db8::1]:5671/prod");
    AXIAM_REQUIRE(endpoint.host == "2001:db8::1");
    AXIAM_REQUIRE(endpoint.port == 5671);
}

AXIAM_TEST("amqps guard: an unusable endpoint fails closed") {
    // A URL this cannot read is not a URL it can vouch for.
    for (const char* url : {"amqps://", "amqps://broker:0", "amqps://broker:99999",
                            "amqps://[2001:db8::1"}) {
        AXIAM_REQUIRE_THROWS_AS(axiam::amqps_endpoint(url), axiam::AuthError);
    }
}

// ---------------------------------------------------------------------------
// The canonical form's own edges
// ---------------------------------------------------------------------------

AXIAM_TEST("reactor: string escaping is serde_json's, not a JSON library's") {
    // The two mandatory escapes, the five short forms, \u00XX for the remaining
    // control characters — and NOTHING else. A forward slash stays literal and
    // UTF-8 passes through unescaped, which is where a naive port diverges and
    // produces a MAC the server will not accept.
    const std::string reason = "a \"quoted\" \\ back\nline\ttab\r\b\f / slash \u0001 ünïcode";
    const std::string canonical = axiam::reactor_canonical_reply(
        correlation_id(), tenant_id(), axiam::kReactorEventLoginPostAuth,
        axiam::ReactorDecision::deny(reason), "n", "2026-07-10T12:00:00Z");

    AXIAM_REQUIRE(canonical.find("\\\"quoted\\\"") != std::string::npos);
    AXIAM_REQUIRE(canonical.find("\\n") != std::string::npos);
    AXIAM_REQUIRE(canonical.find("\\t") != std::string::npos);
    AXIAM_REQUIRE(canonical.find("\\r") != std::string::npos);
    AXIAM_REQUIRE(canonical.find("\\b") != std::string::npos);
    AXIAM_REQUIRE(canonical.find("\\f") != std::string::npos);
    AXIAM_REQUIRE(canonical.find("\\u0001") != std::string::npos);
    // Not escaped: a forward slash, and UTF-8 that passes through as bytes.
    AXIAM_REQUIRE(canonical.find("\\/") == std::string::npos);
    AXIAM_REQUIRE(canonical.find("ünïcode") != std::string::npos);
    // And it is still parseable JSON that round-trips to the same string.
    AXIAM_REQUIRE(json::parse(canonical)["reason"].get<std::string>() == reason);
}

AXIAM_TEST("reactor: a patch key is escaped exactly as a value is") {
    const auto decision = axiam::ReactorDecision::mutate({{"ext.a\"b", "v\nw"}});
    const std::string canonical = axiam::reactor_canonical_reply(
        correlation_id(), tenant_id(), axiam::kReactorEventTokenPreIssue, decision, "n",
        "2026-07-10T12:00:00Z");
    const json parsed = json::parse(canonical);
    AXIAM_REQUIRE(parsed["patch"]["ext.a\"b"].get<std::string>() == "v\nw");
}

AXIAM_TEST("reactor: a patch is emitted in byte order, whatever order it was built in") {
    // std::map is byte-ordered, which is what the server's BTreeMap emits. An
    // unordered container here would produce a MAC that verifies only by luck.
    const auto decision = axiam::ReactorDecision::mutate(
        {{"ext.zulu", "z"}, {"ext.alpha", "a"}, {"ext.mike", "m"}});
    const std::string canonical = axiam::reactor_canonical_reply(
        correlation_id(), tenant_id(), axiam::kReactorEventTokenPreIssue, decision, "n",
        "2026-07-10T12:00:00Z");
    const std::size_t alpha = canonical.find("ext.alpha");
    const std::size_t mike = canonical.find("ext.mike");
    const std::size_t zulu = canonical.find("ext.zulu");
    AXIAM_REQUIRE(alpha < mike);
    AXIAM_REQUIRE(mike < zulu);
}

AXIAM_TEST("reactor: an event missing a signed field is malformed, not badly signed") {
    // Reporting it as a signature failure would send an operator looking at the
    // wrong key for a body the server never sent.
    for (const char* field : {"tenant_id", "event", "correlation_id", "payload", "timeout_ms",
                              "nonce", "issued_at"}) {
        json truncated = vectors()["server_to_reactor"]["login_post_auth"]["message"];
        truncated.erase(field);
        const auto v = axiam::reactor_verify_event(signing_key(), truncated.dump(), tenant_id(),
                                                   verified_at(), nullptr);
        AXIAM_REQUIRE_FALSE(v.ok);
        AXIAM_REQUIRE(v.refusal == axiam::ReactorRefusal::kMalformed);
    }
}

AXIAM_TEST("reactor: a signed field of the wrong type is malformed") {
    json wrong = vectors()["server_to_reactor"]["login_post_auth"]["message"];
    wrong["timeout_ms"] = "1000";  // a string where the server sends a number
    AXIAM_REQUIRE(axiam::reactor_verify_event(signing_key(), wrong.dump(), tenant_id(),
                                              verified_at(), nullptr)
                      .refusal == axiam::ReactorRefusal::kMalformed);
}

AXIAM_TEST("reactor: an event with no hmac_signature at all is refused") {
    json unsigned_body = vectors()["server_to_reactor"]["login_post_auth"]["message"];
    unsigned_body.erase("hmac_signature");
    AXIAM_REQUIRE(axiam::reactor_verify_event(signing_key(), unsigned_body.dump(), tenant_id(),
                                              verified_at(), nullptr)
                      .refusal == axiam::ReactorRefusal::kBadSignature);
}

AXIAM_TEST("reactor: the test signer reproduces the committed vectors") {
    // The premise of every re-signed case below. If this fails, those tests are
    // agreeing with a bug rather than with the server.
    const json& vector = vectors()["server_to_reactor"]["login_post_auth"];
    const json resigned = json::parse(sign_event(vector["message"]));
    AXIAM_REQUIRE(resigned["hmac_signature"].get<std::string>() ==
                  vector["hmac_signature_hex"].get<std::string>());
}

AXIAM_TEST("reactor: an unparseable issued_at is malformed, not stale") {
    // Validly signed, so the MAC is not the defect — a body that got past the MAC
    // and still carries a timestamp nobody can read is malformed, not late, and
    // saying "stale" would send an operator to check clock drift.
    const auto v = axiam::reactor_verify_event(signing_key(), event_at("yesterday"), tenant_id(),
                                               verified_at(), nullptr);
    AXIAM_REQUIRE_FALSE(v.ok);
    AXIAM_REQUIRE(v.refusal == axiam::ReactorRefusal::kMalformed);
}

AXIAM_TEST("reactor: an event naming an unregistered operation is refused AFTER the MAC") {
    // Identity and registry membership come after the MAC: neither is
    // cryptography, and spending them on unauthenticated bytes tells an
    // unauthenticated party what this reactor accepts. This one is validly
    // signed, so the registry check is what actually fires.
    json message = vectors()["server_to_reactor"]["login_post_auth"]["message"];
    message["event"] = "authz.check";  // §22.7: in no registry row
    const auto v = axiam::reactor_verify_event(signing_key(), sign_event(message), tenant_id(),
                                               verified_at(), nullptr);
    AXIAM_REQUIRE_FALSE(v.ok);
    AXIAM_REQUIRE(v.refusal == axiam::ReactorRefusal::kUnknownEvent);
}

AXIAM_TEST("reactor: the runtime's defaults are the real clock and a real nonce source") {
    // The clock and nonce seams exist for §22.13's pinned vectors. A config that
    // sets neither must still work — and the way to see that is a freshly stamped
    // event, which only passes if the runtime is reading the wall clock.
    ScriptedTransport transport({axiam::ReactorDelivery{event_at(rfc3339_now()), "r", ""}});
    axiam::ReactorConfig config;
    config.tenant_id = tenant_id();
    config.reactor_id = vectors()["reactor_id"].get<std::string>();
    config.signing_key = signing_key();

    axiam::reactor_serve(config, transport,
                         [](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                             return axiam::ReactorDecision::allow();
                         });
    AXIAM_REQUIRE(transport.published.size() == 1);

    const json reply = json::parse(transport.published[0].body);
    // A real nonce: 36 characters of UUID, and not the fixture's.
    AXIAM_REQUIRE(reply["nonce"].get<std::string>().size() == 36);
    AXIAM_REQUIRE(reply["nonce"].get<std::string>() != "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb");
    // And a real timestamp, close enough to now to be inside the window the
    // server will apply to it.
    AXIAM_REQUIRE(reply["issued_at"].get<std::string>().size() == 20);
}

AXIAM_TEST("reactor: two deliveries with different nonces both dispatch") {
    // The complement of the replay test: the seen-set must not turn every second
    // delivery away, which is what a set keyed on something other than the nonce
    // would do.
    ScriptedTransport transport({
        axiam::ReactorDelivery{event_at(rfc3339_now(), "11111111-1111-1111-1111-111111111111"),
                               "r", ""},
        axiam::ReactorDelivery{event_at(rfc3339_now(), "22222222-2222-2222-2222-222222222222"),
                               "r", ""},
    });
    axiam::ReactorConfig config;
    config.tenant_id = tenant_id();
    config.signing_key = signing_key();

    int dispatches = 0;
    axiam::reactor_serve(config, transport,
                         [&dispatches](const axiam::ReactorEvent&) -> axiam::ReactorAnswer {
                             ++dispatches;
                             return axiam::ReactorDecision::allow();
                         });
    AXIAM_REQUIRE(dispatches == 2);
    AXIAM_REQUIRE(transport.published.size() == 2);
}


