// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.


#include "axiam/management.hpp"

#include "management_json.hpp"
#include "management_transport.hpp"

// management_json.hpp before management_transport.hpp on purpose: nlohmann finds
// from_json/to_json by ADL at the point a template is INSTANTIATED, and Transport::to_page<T>
// instantiates get<T>() -- so the hooks must already be declared when that header is parsed.

namespace axiam::management {

OrganizationsApi::OrganizationsApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
OrganizationsApi OrganizationsApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return OrganizationsApi(transport_, std::move(next));
}

OrganizationsApi OrganizationsApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return OrganizationsApi(transport_, std::move(next));
}

Page<Organization> OrganizationsApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("organizations.list", "GET", "/api/v1/organizations",
                                            values, query, payload);

    return Transport::to_page<Organization>(response, page);
}

Organization OrganizationsApi::get() {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("organizations.get", "GET", "/api/v1/organizations/{org_id}",
                                            values, query, payload);

    return response.get<Organization>();
}

Organization OrganizationsApi::update(const UpdateOrganizationRequest& body) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("organizations.update", "PUT", "/api/v1/organizations/{org_id}",
                                            values, query, payload);

    return response.get<Organization>();
}

TenantsApi::TenantsApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
TenantsApi TenantsApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return TenantsApi(transport_, std::move(next));
}

TenantsApi TenantsApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return TenantsApi(transport_, std::move(next));
}

Page<Tenant> TenantsApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("tenants.list", "GET", "/api/v1/organizations/{org_id}/tenants",
                                            values, query, payload);

    return Transport::to_page<Tenant>(response, page);
}

Tenant TenantsApi::create(const CreateTenantRequest& body) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("tenants.create", "POST", "/api/v1/organizations/{org_id}/tenants",
                                            values, query, payload);

    return response.get<Tenant>();
}

Tenant TenantsApi::get(const std::string& tenant_id) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}, {"tenant_id", tenant_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("tenants.get", "GET", "/api/v1/organizations/{org_id}/tenants/{tenant_id}",
                                            values, query, payload);

    return response.get<Tenant>();
}

Tenant TenantsApi::update(const std::string& tenant_id, const UpdateTenant& body) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}, {"tenant_id", tenant_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("tenants.update", "PUT", "/api/v1/organizations/{org_id}/tenants/{tenant_id}",
                                            values, query, payload);

    return response.get<Tenant>();
}

void TenantsApi::delete_(const std::string& tenant_id) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}, {"tenant_id", tenant_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("tenants.delete", "DELETE", "/api/v1/organizations/{org_id}/tenants/{tenant_id}",
                                            values, query, payload);
}

UsersApi::UsersApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
UsersApi UsersApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return UsersApi(transport_, std::move(next));
}

UsersApi UsersApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return UsersApi(transport_, std::move(next));
}

Page<UserResponse> UsersApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("users.list", "GET", "/api/v1/users",
                                            values, query, payload);

    return Transport::to_page<UserResponse>(response, page);
}

UserResponse UsersApi::create(const CreateUserRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("users.create", "POST", "/api/v1/users",
                                            values, query, payload);

    return response.get<UserResponse>();
}

UserResponse UsersApi::get(const std::string& user_id) {
    const std::vector<PathValue> values{{"user_id", user_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("users.get", "GET", "/api/v1/users/{user_id}",
                                            values, query, payload);

    return response.get<UserResponse>();
}

UserResponse UsersApi::update(const std::string& user_id, const UpdateUserRequest& body) {
    const std::vector<PathValue> values{{"user_id", user_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("users.update", "PUT", "/api/v1/users/{user_id}",
                                            values, query, payload);

    return response.get<UserResponse>();
}

void UsersApi::delete_(const std::string& user_id) {
    const std::vector<PathValue> values{{"user_id", user_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("users.delete", "DELETE", "/api/v1/users/{user_id}",
                                            values, query, payload);
}

std::vector<MfaMethodResponse> UsersApi::list_mfa_methods(const std::string& user_id) {
    const std::vector<PathValue> values{{"user_id", user_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("users.list_mfa_methods", "GET", "/api/v1/users/{user_id}/mfa-methods",
                                            values, query, payload);

    return response.get<std::vector<MfaMethodResponse>>();
}

void UsersApi::delete_mfa_method(const std::string& user_id, const std::string& method_id) {
    const std::vector<PathValue> values{{"user_id", user_id}, {"method_id", method_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("users.delete_mfa_method", "DELETE", "/api/v1/users/{user_id}/mfa-methods/{method_id}",
                                            values, query, payload);
}

void UsersApi::reset_mfa(const std::string& user_id) {
    const std::vector<PathValue> values{{"user_id", user_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("users.reset_mfa", "POST", "/api/v1/users/{user_id}/reset-mfa",
                                            values, query, payload);
}

UserResponse UsersApi::unlock(const std::string& user_id) {
    const std::vector<PathValue> values{{"user_id", user_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("users.unlock", "POST", "/api/v1/users/{user_id}/unlock",
                                            values, query, payload);

    return response.get<UserResponse>();
}

std::vector<RoleAssignment> UsersApi::list_roles(const std::string& user_id) {
    const std::vector<PathValue> values{{"user_id", user_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("users.list_roles", "GET", "/api/v1/users/{user_id}/roles",
                                            values, query, payload);

    return response.get<std::vector<RoleAssignment>>();
}

GroupsApi::GroupsApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
GroupsApi GroupsApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return GroupsApi(transport_, std::move(next));
}

GroupsApi GroupsApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return GroupsApi(transport_, std::move(next));
}

Page<Group> GroupsApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("groups.list", "GET", "/api/v1/groups",
                                            values, query, payload);

    return Transport::to_page<Group>(response, page);
}

Group GroupsApi::create(const CreateGroupRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("groups.create", "POST", "/api/v1/groups",
                                            values, query, payload);

    return response.get<Group>();
}

Group GroupsApi::get(const std::string& group_id) {
    const std::vector<PathValue> values{{"group_id", group_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("groups.get", "GET", "/api/v1/groups/{group_id}",
                                            values, query, payload);

    return response.get<Group>();
}

Group GroupsApi::update(const std::string& group_id, const UpdateGroup& body) {
    const std::vector<PathValue> values{{"group_id", group_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("groups.update", "PUT", "/api/v1/groups/{group_id}",
                                            values, query, payload);

    return response.get<Group>();
}

void GroupsApi::delete_(const std::string& group_id) {
    const std::vector<PathValue> values{{"group_id", group_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("groups.delete", "DELETE", "/api/v1/groups/{group_id}",
                                            values, query, payload);
}

Page<UserResponse> GroupsApi::list_members(const std::string& group_id, const PageRequest& page) {
    const std::vector<PathValue> values{{"group_id", group_id}};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("groups.list_members", "GET", "/api/v1/groups/{group_id}/members",
                                            values, query, payload);

    return Transport::to_page<UserResponse>(response, page);
}

void GroupsApi::add_member(const std::string& group_id, const AddMemberRequest& body) {
    const std::vector<PathValue> values{{"group_id", group_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    transport_->send("groups.add_member", "POST", "/api/v1/groups/{group_id}/members",
                                            values, query, payload);
}

void GroupsApi::remove_member(const std::string& group_id, const std::string& user_id) {
    const std::vector<PathValue> values{{"group_id", group_id}, {"user_id", user_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("groups.remove_member", "DELETE", "/api/v1/groups/{group_id}/members/{user_id}",
                                            values, query, payload);
}

std::vector<RoleAssignment> GroupsApi::list_roles(const std::string& group_id) {
    const std::vector<PathValue> values{{"group_id", group_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("groups.list_roles", "GET", "/api/v1/groups/{group_id}/roles",
                                            values, query, payload);

    return response.get<std::vector<RoleAssignment>>();
}

RolesApi::RolesApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
RolesApi RolesApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return RolesApi(transport_, std::move(next));
}

RolesApi RolesApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return RolesApi(transport_, std::move(next));
}

Page<Role> RolesApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("roles.list", "GET", "/api/v1/roles",
                                            values, query, payload);

    return Transport::to_page<Role>(response, page);
}

Role RolesApi::create(const CreateRoleRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("roles.create", "POST", "/api/v1/roles",
                                            values, query, payload);

    return response.get<Role>();
}

Role RolesApi::get(const std::string& role_id) {
    const std::vector<PathValue> values{{"role_id", role_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("roles.get", "GET", "/api/v1/roles/{role_id}",
                                            values, query, payload);

    return response.get<Role>();
}

Role RolesApi::update(const std::string& role_id, const UpdateRole& body) {
    const std::vector<PathValue> values{{"role_id", role_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("roles.update", "PUT", "/api/v1/roles/{role_id}",
                                            values, query, payload);

    return response.get<Role>();
}

void RolesApi::delete_(const std::string& role_id) {
    const std::vector<PathValue> values{{"role_id", role_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("roles.delete", "DELETE", "/api/v1/roles/{role_id}",
                                            values, query, payload);
}

std::vector<RoleUserAssignment> RolesApi::list_users(const std::string& role_id) {
    const std::vector<PathValue> values{{"role_id", role_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("roles.list_users", "GET", "/api/v1/roles/{role_id}/users",
                                            values, query, payload);

    return response.get<std::vector<RoleUserAssignment>>();
}

void RolesApi::assign_to_user(const std::string& role_id, const AssignRoleToUserRequest& body) {
    const std::vector<PathValue> values{{"role_id", role_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    transport_->send("roles.assign_to_user", "POST", "/api/v1/roles/{role_id}/users",
                                            values, query, payload);
}

void RolesApi::unassign_from_user(const std::string& role_id, const std::string& user_id, const std::optional<std::string>& resource_id) {
    const std::vector<PathValue> values{{"role_id", role_id}, {"user_id", user_id}};
    const std::vector<QueryValue> query{{"resource_id", resource_id}};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("roles.unassign_from_user", "DELETE", "/api/v1/roles/{role_id}/users/{user_id}",
                                            values, query, payload);
}

std::vector<RoleGroupAssignment> RolesApi::list_groups(const std::string& role_id) {
    const std::vector<PathValue> values{{"role_id", role_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("roles.list_groups", "GET", "/api/v1/roles/{role_id}/groups",
                                            values, query, payload);

    return response.get<std::vector<RoleGroupAssignment>>();
}

void RolesApi::assign_to_group(const std::string& role_id, const AssignRoleToGroupRequest& body) {
    const std::vector<PathValue> values{{"role_id", role_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    transport_->send("roles.assign_to_group", "POST", "/api/v1/roles/{role_id}/groups",
                                            values, query, payload);
}

void RolesApi::unassign_from_group(const std::string& role_id, const std::string& group_id, const std::optional<std::string>& resource_id) {
    const std::vector<PathValue> values{{"role_id", role_id}, {"group_id", group_id}};
    const std::vector<QueryValue> query{{"resource_id", resource_id}};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("roles.unassign_from_group", "DELETE", "/api/v1/roles/{role_id}/groups/{group_id}",
                                            values, query, payload);
}

std::vector<ResolvedPermissionGrant> RolesApi::list_permissions(const std::string& role_id) {
    const std::vector<PathValue> values{{"role_id", role_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("roles.list_permissions", "GET", "/api/v1/roles/{role_id}/permissions",
                                            values, query, payload);

    return response.get<std::vector<ResolvedPermissionGrant>>();
}

void RolesApi::grant_permission(const std::string& role_id, const GrantPermissionRequest& body) {
    const std::vector<PathValue> values{{"role_id", role_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    transport_->send("roles.grant_permission", "POST", "/api/v1/roles/{role_id}/permissions",
                                            values, query, payload);
}

void RolesApi::revoke_permission(const std::string& role_id, const std::string& permission_id) {
    const std::vector<PathValue> values{{"role_id", role_id}, {"permission_id", permission_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("roles.revoke_permission", "DELETE", "/api/v1/roles/{role_id}/permissions/{permission_id}",
                                            values, query, payload);
}

PermissionsApi::PermissionsApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
PermissionsApi PermissionsApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return PermissionsApi(transport_, std::move(next));
}

PermissionsApi PermissionsApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return PermissionsApi(transport_, std::move(next));
}

Page<Permission> PermissionsApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("permissions.list", "GET", "/api/v1/permissions",
                                            values, query, payload);

    return Transport::to_page<Permission>(response, page);
}

Permission PermissionsApi::create(const CreatePermissionRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("permissions.create", "POST", "/api/v1/permissions",
                                            values, query, payload);

    return response.get<Permission>();
}

Permission PermissionsApi::get(const std::string& permission_id) {
    const std::vector<PathValue> values{{"permission_id", permission_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("permissions.get", "GET", "/api/v1/permissions/{permission_id}",
                                            values, query, payload);

    return response.get<Permission>();
}

Permission PermissionsApi::update(const std::string& permission_id, const UpdatePermissionRequest& body) {
    const std::vector<PathValue> values{{"permission_id", permission_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("permissions.update", "PUT", "/api/v1/permissions/{permission_id}",
                                            values, query, payload);

    return response.get<Permission>();
}

void PermissionsApi::delete_(const std::string& permission_id) {
    const std::vector<PathValue> values{{"permission_id", permission_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("permissions.delete", "DELETE", "/api/v1/permissions/{permission_id}",
                                            values, query, payload);
}

ResourcesApi::ResourcesApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
ResourcesApi ResourcesApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return ResourcesApi(transport_, std::move(next));
}

ResourcesApi ResourcesApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return ResourcesApi(transport_, std::move(next));
}

Page<Resource> ResourcesApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("resources.list", "GET", "/api/v1/resources",
                                            values, query, payload);

    return Transport::to_page<Resource>(response, page);
}

Resource ResourcesApi::create(const CreateResourceRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("resources.create", "POST", "/api/v1/resources",
                                            values, query, payload);

    return response.get<Resource>();
}

Resource ResourcesApi::get(const std::string& resource_id) {
    const std::vector<PathValue> values{{"resource_id", resource_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("resources.get", "GET", "/api/v1/resources/{resource_id}",
                                            values, query, payload);

    return response.get<Resource>();
}

Resource ResourcesApi::update(const std::string& resource_id, const UpdateResourceRequest& body) {
    const std::vector<PathValue> values{{"resource_id", resource_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("resources.update", "PUT", "/api/v1/resources/{resource_id}",
                                            values, query, payload);

    return response.get<Resource>();
}

void ResourcesApi::delete_(const std::string& resource_id) {
    const std::vector<PathValue> values{{"resource_id", resource_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("resources.delete", "DELETE", "/api/v1/resources/{resource_id}",
                                            values, query, payload);
}

std::vector<Resource> ResourcesApi::list_children(const std::string& resource_id) {
    const std::vector<PathValue> values{{"resource_id", resource_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("resources.list_children", "GET", "/api/v1/resources/{resource_id}/children",
                                            values, query, payload);

    return response.get<std::vector<Resource>>();
}

std::vector<Resource> ResourcesApi::list_ancestors(const std::string& resource_id) {
    const std::vector<PathValue> values{{"resource_id", resource_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("resources.list_ancestors", "GET", "/api/v1/resources/{resource_id}/ancestors",
                                            values, query, payload);

    return response.get<std::vector<Resource>>();
}

ScopesApi::ScopesApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
ScopesApi ScopesApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return ScopesApi(transport_, std::move(next));
}

ScopesApi ScopesApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return ScopesApi(transport_, std::move(next));
}

std::vector<Scope> ScopesApi::list(const std::string& resource_id) {
    const std::vector<PathValue> values{{"resource_id", resource_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("scopes.list", "GET", "/api/v1/resources/{resource_id}/scopes",
                                            values, query, payload);

    return response.get<std::vector<Scope>>();
}

Scope ScopesApi::create(const std::string& resource_id, const CreateScopeRequest& body) {
    const std::vector<PathValue> values{{"resource_id", resource_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("scopes.create", "POST", "/api/v1/resources/{resource_id}/scopes",
                                            values, query, payload);

    return response.get<Scope>();
}

Scope ScopesApi::get(const std::string& resource_id, const std::string& scope_id) {
    const std::vector<PathValue> values{{"resource_id", resource_id}, {"scope_id", scope_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("scopes.get", "GET", "/api/v1/resources/{resource_id}/scopes/{scope_id}",
                                            values, query, payload);

    return response.get<Scope>();
}

Scope ScopesApi::update(const std::string& resource_id, const std::string& scope_id, const UpdateScopeRequest& body) {
    const std::vector<PathValue> values{{"resource_id", resource_id}, {"scope_id", scope_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("scopes.update", "PUT", "/api/v1/resources/{resource_id}/scopes/{scope_id}",
                                            values, query, payload);

    return response.get<Scope>();
}

void ScopesApi::delete_(const std::string& resource_id, const std::string& scope_id) {
    const std::vector<PathValue> values{{"resource_id", resource_id}, {"scope_id", scope_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("scopes.delete", "DELETE", "/api/v1/resources/{resource_id}/scopes/{scope_id}",
                                            values, query, payload);
}

ServiceAccountsApi::ServiceAccountsApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
ServiceAccountsApi ServiceAccountsApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return ServiceAccountsApi(transport_, std::move(next));
}

ServiceAccountsApi ServiceAccountsApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return ServiceAccountsApi(transport_, std::move(next));
}

Page<ServiceAccountResponse> ServiceAccountsApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("service_accounts.list", "GET", "/api/v1/service-accounts",
                                            values, query, payload);

    return Transport::to_page<ServiceAccountResponse>(response, page);
}

ServiceAccountCreatedResponse ServiceAccountsApi::create(const CreateServiceAccountRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("service_accounts.create", "POST", "/api/v1/service-accounts",
                                            values, query, payload);

    return response.get<ServiceAccountCreatedResponse>();
}

ServiceAccountResponse ServiceAccountsApi::get(const std::string& sa_id) {
    const std::vector<PathValue> values{{"sa_id", sa_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("service_accounts.get", "GET", "/api/v1/service-accounts/{sa_id}",
                                            values, query, payload);

    return response.get<ServiceAccountResponse>();
}

ServiceAccountResponse ServiceAccountsApi::update(const std::string& sa_id, const UpdateServiceAccount& body) {
    const std::vector<PathValue> values{{"sa_id", sa_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("service_accounts.update", "PUT", "/api/v1/service-accounts/{sa_id}",
                                            values, query, payload);

    return response.get<ServiceAccountResponse>();
}

void ServiceAccountsApi::delete_(const std::string& sa_id) {
    const std::vector<PathValue> values{{"sa_id", sa_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("service_accounts.delete", "DELETE", "/api/v1/service-accounts/{sa_id}",
                                            values, query, payload);
}

RotateSecretResponse ServiceAccountsApi::rotate_secret(const std::string& sa_id) {
    const std::vector<PathValue> values{{"sa_id", sa_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("service_accounts.rotate_secret", "POST", "/api/v1/service-accounts/{sa_id}/rotate-secret",
                                            values, query, payload);

    return response.get<RotateSecretResponse>();
}

void ServiceAccountsApi::bind_certificate(const std::string& sa_id, const BindCertificate& body) {
    const std::vector<PathValue> values{{"sa_id", sa_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    transport_->send("service_accounts.bind_certificate", "POST", "/api/v1/service-accounts/{sa_id}/bind-certificate",
                                            values, query, payload);
}

CertificatesApi::CertificatesApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
CertificatesApi CertificatesApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return CertificatesApi(transport_, std::move(next));
}

CertificatesApi CertificatesApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return CertificatesApi(transport_, std::move(next));
}

Page<Certificate> CertificatesApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("certificates.list", "GET", "/api/v1/certificates",
                                            values, query, payload);

    return Transport::to_page<Certificate>(response, page);
}

GeneratedCertificate CertificatesApi::generate(const CreateCertificateRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("certificates.generate", "POST", "/api/v1/certificates",
                                            values, query, payload);

    return response.get<GeneratedCertificate>();
}

Certificate CertificatesApi::get(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("certificates.get", "GET", "/api/v1/certificates/{id}",
                                            values, query, payload);

    return response.get<Certificate>();
}

void CertificatesApi::revoke(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("certificates.revoke", "POST", "/api/v1/certificates/{id}/revoke",
                                            values, query, payload);
}

CaCertificatesApi::CaCertificatesApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
CaCertificatesApi CaCertificatesApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return CaCertificatesApi(transport_, std::move(next));
}

CaCertificatesApi CaCertificatesApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return CaCertificatesApi(transport_, std::move(next));
}

Page<CaCertificate> CaCertificatesApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("ca_certificates.list", "GET", "/api/v1/organizations/{org_id}/ca-certificates",
                                            values, query, payload);

    return Transport::to_page<CaCertificate>(response, page);
}

GeneratedCaCertificate CaCertificatesApi::generate(const CreateCaCertificateRequest& body) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("ca_certificates.generate", "POST", "/api/v1/organizations/{org_id}/ca-certificates",
                                            values, query, payload);

    return response.get<GeneratedCaCertificate>();
}

CaCertificate CaCertificatesApi::import_ca(const ImportCaCertificateRequest& body) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("ca_certificates.import_ca", "POST", "/api/v1/organizations/{org_id}/ca-certificates/import",
                                            values, query, payload);

    return response.get<CaCertificate>();
}

CaCertificate CaCertificatesApi::get(const std::string& id) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}, {"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("ca_certificates.get", "GET", "/api/v1/organizations/{org_id}/ca-certificates/{id}",
                                            values, query, payload);

    return response.get<CaCertificate>();
}

void CaCertificatesApi::revoke(const std::string& id) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}, {"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("ca_certificates.revoke", "POST", "/api/v1/organizations/{org_id}/ca-certificates/{id}/revoke",
                                            values, query, payload);
}

MigrateCustodyResponse CaCertificatesApi::migrate_custody(const std::string& id) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}, {"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("ca_certificates.migrate_custody", "POST", "/api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody",
                                            values, query, payload);

    return response.get<MigrateCustodyResponse>();
}

MtlsTrustAnchorResponse CaCertificatesApi::set_mtls_trust_anchor(const std::string& id, const SetMtlsTrustAnchor& body) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}, {"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("ca_certificates.set_mtls_trust_anchor", "PUT", "/api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor",
                                            values, query, payload);

    return response.get<MtlsTrustAnchorResponse>();
}

Page<CaCertificate> CaCertificatesApi::list_signing_cas(const std::string& tenant_id, const PageRequest& page) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}, {"tenant_id", tenant_id}};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("ca_certificates.list_signing_cas", "GET", "/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas",
                                            values, query, payload);

    return Transport::to_page<CaCertificate>(response, page);
}

GeneratedCaCertificate CaCertificatesApi::generate_signing_ca(const std::string& tenant_id, const CreateIntermediateCaRequest& body) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}, {"tenant_id", tenant_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("ca_certificates.generate_signing_ca", "POST", "/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas",
                                            values, query, payload);

    return response.get<GeneratedCaCertificate>();
}

CaCertificate CaCertificatesApi::sign_signing_ca_csr(const std::string& tenant_id, const SignIntermediateCsrRequest& body) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}, {"tenant_id", tenant_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("ca_certificates.sign_signing_ca_csr", "POST", "/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr",
                                            values, query, payload);

    return response.get<CaCertificate>();
}

PgpKeysApi::PgpKeysApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
PgpKeysApi PgpKeysApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return PgpKeysApi(transport_, std::move(next));
}

PgpKeysApi PgpKeysApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return PgpKeysApi(transport_, std::move(next));
}

Page<PgpKey> PgpKeysApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("pgp_keys.list", "GET", "/api/v1/pgp-keys",
                                            values, query, payload);

    return Transport::to_page<PgpKey>(response, page);
}

GeneratedPgpKey PgpKeysApi::generate(const CreatePgpKeyRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("pgp_keys.generate", "POST", "/api/v1/pgp-keys",
                                            values, query, payload);

    return response.get<GeneratedPgpKey>();
}

PgpKey PgpKeysApi::get(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("pgp_keys.get", "GET", "/api/v1/pgp-keys/{id}",
                                            values, query, payload);

    return response.get<PgpKey>();
}

void PgpKeysApi::revoke(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("pgp_keys.revoke", "POST", "/api/v1/pgp-keys/{id}/revoke",
                                            values, query, payload);
}

EncryptedExport PgpKeysApi::encrypt(const std::string& id, const EncryptRequest& body) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("pgp_keys.encrypt", "POST", "/api/v1/pgp-keys/{id}/encrypt",
                                            values, query, payload);

    return response.get<EncryptedExport>();
}

SignedAuditBatch PgpKeysApi::sign_audit_batch(const SignAuditBatchRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("pgp_keys.sign_audit_batch", "POST", "/api/v1/pgp-keys/sign-audit-batch",
                                            values, query, payload);

    return response.get<SignedAuditBatch>();
}

WebhooksApi::WebhooksApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
WebhooksApi WebhooksApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return WebhooksApi(transport_, std::move(next));
}

WebhooksApi WebhooksApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return WebhooksApi(transport_, std::move(next));
}

Page<WebhookResponse> WebhooksApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("webhooks.list", "GET", "/api/v1/webhooks",
                                            values, query, payload);

    return Transport::to_page<WebhookResponse>(response, page);
}

WebhookResponse WebhooksApi::create(const CreateWebhookRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("webhooks.create", "POST", "/api/v1/webhooks",
                                            values, query, payload);

    return response.get<WebhookResponse>();
}

WebhookResponse WebhooksApi::get(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("webhooks.get", "GET", "/api/v1/webhooks/{id}",
                                            values, query, payload);

    return response.get<WebhookResponse>();
}

WebhookResponse WebhooksApi::update(const std::string& id, const UpdateWebhookRequest& body) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("webhooks.update", "PUT", "/api/v1/webhooks/{id}",
                                            values, query, payload);

    return response.get<WebhookResponse>();
}

void WebhooksApi::delete_(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("webhooks.delete", "DELETE", "/api/v1/webhooks/{id}",
                                            values, query, payload);
}

Oauth2ClientsApi::Oauth2ClientsApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
Oauth2ClientsApi Oauth2ClientsApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return Oauth2ClientsApi(transport_, std::move(next));
}

Oauth2ClientsApi Oauth2ClientsApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return Oauth2ClientsApi(transport_, std::move(next));
}

Page<OAuth2ClientResponse> Oauth2ClientsApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("oauth2_clients.list", "GET", "/api/v1/oauth2-clients",
                                            values, query, payload);

    return Transport::to_page<OAuth2ClientResponse>(response, page);
}

OAuth2ClientCreatedResponse Oauth2ClientsApi::create(const CreateOAuth2ClientRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("oauth2_clients.create", "POST", "/api/v1/oauth2-clients",
                                            values, query, payload);

    return response.get<OAuth2ClientCreatedResponse>();
}

OAuth2ClientResponse Oauth2ClientsApi::get(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("oauth2_clients.get", "GET", "/api/v1/oauth2-clients/{id}",
                                            values, query, payload);

    return response.get<OAuth2ClientResponse>();
}

OAuth2ClientResponse Oauth2ClientsApi::update(const std::string& id, const UpdateOAuth2ClientRequest& body) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("oauth2_clients.update", "PUT", "/api/v1/oauth2-clients/{id}",
                                            values, query, payload);

    return response.get<OAuth2ClientResponse>();
}

void Oauth2ClientsApi::delete_(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("oauth2_clients.delete", "DELETE", "/api/v1/oauth2-clients/{id}",
                                            values, query, payload);
}

FederationApi::FederationApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
FederationApi FederationApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return FederationApi(transport_, std::move(next));
}

FederationApi FederationApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return FederationApi(transport_, std::move(next));
}

Page<FederationConfigResponse> FederationApi::list_configs(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("federation.list_configs", "GET", "/api/v1/federation-configs",
                                            values, query, payload);

    return Transport::to_page<FederationConfigResponse>(response, page);
}

FederationConfigResponse FederationApi::create_config(const CreateFederationConfigRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("federation.create_config", "POST", "/api/v1/federation-configs",
                                            values, query, payload);

    return response.get<FederationConfigResponse>();
}

FederationConfigResponse FederationApi::get_config(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("federation.get_config", "GET", "/api/v1/federation-configs/{id}",
                                            values, query, payload);

    return response.get<FederationConfigResponse>();
}

FederationConfigResponse FederationApi::update_config(const std::string& id, const UpdateFederationConfigRequest& body) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("federation.update_config", "PUT", "/api/v1/federation-configs/{id}",
                                            values, query, payload);

    return response.get<FederationConfigResponse>();
}

void FederationApi::delete_config(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("federation.delete_config", "DELETE", "/api/v1/federation-configs/{id}",
                                            values, query, payload);
}

std::vector<FederationLinkResponse> FederationApi::list_user_links(const std::string& user_id) {
    const std::vector<PathValue> values{{"user_id", user_id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("federation.list_user_links", "GET", "/api/v1/federation-links/user/{user_id}",
                                            values, query, payload);

    return response.get<std::vector<FederationLinkResponse>>();
}

void FederationApi::delete_link(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("federation.delete_link", "DELETE", "/api/v1/federation-links/{id}",
                                            values, query, payload);
}

OidcAuthorizeResponse FederationApi::oidc_authorize(const OidcAuthorizeRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("federation.oidc_authorize", "POST", "/api/v1/federation/oidc/authorize",
                                            values, query, payload);

    return response.get<OidcAuthorizeResponse>();
}

OidcCallbackResponse FederationApi::oidc_callback(const OidcCallbackRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("federation.oidc_callback", "POST", "/api/v1/federation/oidc/callback",
                                            values, query, payload);

    return response.get<OidcCallbackResponse>();
}

NotificationRulesApi::NotificationRulesApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
NotificationRulesApi NotificationRulesApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return NotificationRulesApi(transport_, std::move(next));
}

NotificationRulesApi NotificationRulesApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return NotificationRulesApi(transport_, std::move(next));
}

Page<NotificationRuleResponse> NotificationRulesApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("notification_rules.list", "GET", "/api/v1/notification-rules",
                                            values, query, payload);

    return Transport::to_page<NotificationRuleResponse>(response, page);
}

NotificationRuleResponse NotificationRulesApi::create(const CreateNotificationRuleRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("notification_rules.create", "POST", "/api/v1/notification-rules",
                                            values, query, payload);

    return response.get<NotificationRuleResponse>();
}

NotificationRuleResponse NotificationRulesApi::get(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("notification_rules.get", "GET", "/api/v1/notification-rules/{id}",
                                            values, query, payload);

    return response.get<NotificationRuleResponse>();
}

NotificationRuleResponse NotificationRulesApi::update(const std::string& id, const UpdateNotificationRuleRequest& body) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("notification_rules.update", "PUT", "/api/v1/notification-rules/{id}",
                                            values, query, payload);

    return response.get<NotificationRuleResponse>();
}

void NotificationRulesApi::delete_(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("notification_rules.delete", "DELETE", "/api/v1/notification-rules/{id}",
                                            values, query, payload);
}

EmailConfigApi::EmailConfigApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
EmailConfigApi EmailConfigApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return EmailConfigApi(transport_, std::move(next));
}

EmailConfigApi EmailConfigApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return EmailConfigApi(transport_, std::move(next));
}

EmailConfig EmailConfigApi::get_org() {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("email_config.get_org", "GET", "/api/v1/organizations/{org_id}/email-config",
                                            values, query, payload);

    return response.get<EmailConfig>();
}

EmailConfig EmailConfigApi::set_org(const SetOrgEmailConfig& body) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("email_config.set_org", "PUT", "/api/v1/organizations/{org_id}/email-config",
                                            values, query, payload);

    return response.get<EmailConfig>();
}

void EmailConfigApi::delete_org() {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("email_config.delete_org", "DELETE", "/api/v1/organizations/{org_id}/email-config",
                                            values, query, payload);
}

EmailTestResult EmailConfigApi::test_org() {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("email_config.test_org", "POST", "/api/v1/organizations/{org_id}/email-config/test",
                                            values, query, payload);

    return response.get<EmailTestResult>();
}

EmailConfigOverride EmailConfigApi::get_tenant() {
    const std::vector<PathValue> values{{"tenant_id", transport_->tenant_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("email_config.get_tenant", "GET", "/api/v1/tenants/{tenant_id}/email-config",
                                            values, query, payload);

    return response.get<EmailConfigOverride>();
}

EmailConfigOverride EmailConfigApi::set_tenant(const EmailConfigOverride& body) {
    const std::vector<PathValue> values{{"tenant_id", transport_->tenant_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("email_config.set_tenant", "PUT", "/api/v1/tenants/{tenant_id}/email-config",
                                            values, query, payload);

    return response.get<EmailConfigOverride>();
}

void EmailConfigApi::delete_tenant() {
    const std::vector<PathValue> values{{"tenant_id", transport_->tenant_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("email_config.delete_tenant", "DELETE", "/api/v1/tenants/{tenant_id}/email-config",
                                            values, query, payload);
}

EmailTestResult EmailConfigApi::test_tenant() {
    const std::vector<PathValue> values{{"tenant_id", transport_->tenant_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("email_config.test_tenant", "POST", "/api/v1/tenants/{tenant_id}/email-config/test",
                                            values, query, payload);

    return response.get<EmailTestResult>();
}

SettingsApi::SettingsApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
SettingsApi SettingsApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return SettingsApi(transport_, std::move(next));
}

SettingsApi SettingsApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return SettingsApi(transport_, std::move(next));
}

SecuritySettings SettingsApi::get_org() {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("settings.get_org", "GET", "/api/v1/organizations/{org_id}/settings",
                                            values, query, payload);

    return response.get<SecuritySettings>();
}

SecuritySettings SettingsApi::set_org(const SetOrgSettings& body) {
    const std::vector<PathValue> values{{"org_id", transport_->org_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("settings.set_org", "PUT", "/api/v1/organizations/{org_id}/settings",
                                            values, query, payload);

    return response.get<SecuritySettings>();
}

SecuritySettings SettingsApi::get_effective() {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("settings.get_effective", "GET", "/api/v1/settings",
                                            values, query, payload);

    return response.get<SecuritySettings>();
}

SecuritySettings SettingsApi::set_effective(const TenantSettingsOverride& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("settings.set_effective", "PUT", "/api/v1/settings",
                                            values, query, payload);

    return response.get<SecuritySettings>();
}

TenantSettingsOverride SettingsApi::get_tenant_override() {
    const std::vector<PathValue> values{{"tenant_id", transport_->tenant_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("settings.get_tenant_override", "GET", "/api/v1/tenants/{tenant_id}/settings",
                                            values, query, payload);

    return response.get<TenantSettingsOverride>();
}

TenantSettingsOverride SettingsApi::set_tenant_override(const TenantSettingsOverride& body) {
    const std::vector<PathValue> values{{"tenant_id", transport_->tenant_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("settings.set_tenant_override", "PUT", "/api/v1/tenants/{tenant_id}/settings",
                                            values, query, payload);

    return response.get<TenantSettingsOverride>();
}

void SettingsApi::delete_tenant_override() {
    const std::vector<PathValue> values{{"tenant_id", transport_->tenant_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("settings.delete_tenant_override", "DELETE", "/api/v1/tenants/{tenant_id}/settings",
                                            values, query, payload);
}

ScimTokensApi::ScimTokensApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
ScimTokensApi ScimTokensApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return ScimTokensApi(transport_, std::move(next));
}

ScimTokensApi ScimTokensApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return ScimTokensApi(transport_, std::move(next));
}

std::vector<ScimTokenResponse> ScimTokensApi::list() {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("scim_tokens.list", "GET", "/api/v1/scim-tokens",
                                            values, query, payload);

    return response.get<std::vector<ScimTokenResponse>>();
}

CreateScimTokenResponse ScimTokensApi::create(const CreateScimTokenRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("scim_tokens.create", "POST", "/api/v1/scim-tokens",
                                            values, query, payload);

    return response.get<CreateScimTokenResponse>();
}

void ScimTokensApi::revoke(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("scim_tokens.revoke", "DELETE", "/api/v1/scim-tokens/{id}",
                                            values, query, payload);
}

ReactorsApi::ReactorsApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
ReactorsApi ReactorsApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return ReactorsApi(transport_, std::move(next));
}

ReactorsApi ReactorsApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return ReactorsApi(transport_, std::move(next));
}

Page<ReactorResponse> ReactorsApi::list(const PageRequest& page) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("reactors.list", "GET", "/api/v1/reactors",
                                            values, query, payload);

    return Transport::to_page<ReactorResponse>(response, page);
}

ReactorResponse ReactorsApi::create(const CreateReactorRequest& body) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("reactors.create", "POST", "/api/v1/reactors",
                                            values, query, payload);

    return response.get<ReactorResponse>();
}

ReactorResponse ReactorsApi::get(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("reactors.get", "GET", "/api/v1/reactors/{id}",
                                            values, query, payload);

    return response.get<ReactorResponse>();
}

ReactorResponse ReactorsApi::update(const std::string& id, const UpdateReactorRequest& body) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("reactors.update", "PUT", "/api/v1/reactors/{id}",
                                            values, query, payload);

    return response.get<ReactorResponse>();
}

void ReactorsApi::delete_(const std::string& id) {
    const std::vector<PathValue> values{{"id", id}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("reactors.delete", "DELETE", "/api/v1/reactors/{id}",
                                            values, query, payload);
}

std::vector<ReactorEventDescriptor> ReactorsApi::list_events() {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("reactors.list_events", "GET", "/api/v1/reactors/events",
                                            values, query, payload);

    return response.get<std::vector<ReactorEventDescriptor>>();
}

WebauthnPolicyApi::WebauthnPolicyApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
WebauthnPolicyApi WebauthnPolicyApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return WebauthnPolicyApi(transport_, std::move(next));
}

WebauthnPolicyApi WebauthnPolicyApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return WebauthnPolicyApi(transport_, std::move(next));
}

PolicyResponse WebauthnPolicyApi::get() {
    const std::vector<PathValue> values{{"tenant_id", transport_->tenant_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("webauthn_policy.get", "GET", "/api/v1/tenants/{tenant_id}/webauthn/attestation-policy",
                                            values, query, payload);

    return response.get<PolicyResponse>();
}

WebauthnAttestationPolicy WebauthnPolicyApi::set(const WebauthnAttestationPolicy& body) {
    const std::vector<PathValue> values{{"tenant_id", transport_->tenant_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = nlohmann::json(body);
    const auto response = transport_->send("webauthn_policy.set", "PUT", "/api/v1/tenants/{tenant_id}/webauthn/attestation-policy",
                                            values, query, payload);

    return response.get<WebauthnAttestationPolicy>();
}

std::vector<ComplianceReportEntry> WebauthnPolicyApi::compliance_report() {
    const std::vector<PathValue> values{{"tenant_id", transport_->tenant_id(scope_)}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("webauthn_policy.compliance_report", "GET", "/api/v1/tenants/{tenant_id}/webauthn/compliance-report",
                                            values, query, payload);

    return response.get<std::vector<ComplianceReportEntry>>();
}

AuditApi::AuditApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
AuditApi AuditApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return AuditApi(transport_, std::move(next));
}

AuditApi AuditApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return AuditApi(transport_, std::move(next));
}

Page<AuditLogEntry> AuditApi::list(const PageRequest& page, const std::optional<std::string>& actor_id, const std::optional<std::string>& action, const std::optional<std::string>& outcome, const std::optional<std::string>& resource_id, const std::optional<std::string>& from, const std::optional<std::string>& to) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    query.push_back({"actor_id", actor_id});
    query.push_back({"action", action});
    query.push_back({"outcome", outcome});
    query.push_back({"resource_id", resource_id});
    query.push_back({"from", from});
    query.push_back({"to", to});
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("audit.list", "GET", "/api/v1/audit-logs",
                                            values, query, payload);

    return Transport::to_page<AuditLogEntry>(response, page);
}

Page<AuditLogEntry> AuditApi::list_system(const PageRequest& page, const std::optional<std::string>& actor_id, const std::optional<std::string>& action, const std::optional<std::string>& outcome, const std::optional<std::string>& resource_id, const std::optional<std::string>& from, const std::optional<std::string>& to) {
    const std::vector<PathValue> values{};
    auto query = Transport::paging(page);
    query.push_back({"actor_id", actor_id});
    query.push_back({"action", action});
    query.push_back({"outcome", outcome});
    query.push_back({"resource_id", resource_id});
    query.push_back({"from", from});
    query.push_back({"to", to});
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("audit.list_system", "GET", "/api/v1/audit-logs/system",
                                            values, query, payload);

    return Transport::to_page<AuditLogEntry>(response, page);
}

PrivacyApi::PrivacyApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
PrivacyApi PrivacyApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return PrivacyApi(transport_, std::move(next));
}

PrivacyApi PrivacyApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return PrivacyApi(transport_, std::move(next));
}

void PrivacyApi::request_export() {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("privacy.request_export", "POST", "/api/v1/account/export",
                                            values, query, payload);
}

void PrivacyApi::download_export(const std::string& token) {
    const std::vector<PathValue> values{{"token", token}};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("privacy.download_export", "GET", "/api/v1/account/export/{token}",
                                            values, query, payload);
}

void PrivacyApi::request_delete() {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("privacy.request_delete", "POST", "/api/v1/account/delete",
                                            values, query, payload);
}

void PrivacyApi::cancel_delete(const std::string& token) {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{{"token", token}};
    const std::optional<nlohmann::json> payload = std::nullopt;
    transport_->send("privacy.cancel_delete", "GET", "/api/v1/auth/account/delete/cancel",
                                            values, query, payload);
}

PlatformApi::PlatformApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

// A COPY, not a mutation. §27.4 rule 3: an administrator holding a handle to their own tenant
// should not find it repointed at someone else's because an unrelated code path re-scoped a
// shared object -- and on a management surface that failure mode writes to the wrong tenant
// rather than merely reading.
PlatformApi PlatformApi::in_org(std::string org) const {
    CallScope next = scope_;
    next.org_id = std::move(org);
    return PlatformApi(transport_, std::move(next));
}

PlatformApi PlatformApi::for_tenant(std::string tenant) const {
    CallScope next = scope_;
    next.tenant_id = std::move(tenant);
    return PlatformApi(transport_, std::move(next));
}

HealthResponse PlatformApi::health() {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("platform.health", "GET", "/health",
                                            values, query, payload);

    return response.get<HealthResponse>();
}

ReadyResponse PlatformApi::ready() {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("platform.ready", "GET", "/ready",
                                            values, query, payload);

    return response.get<ReadyResponse>();
}

MdsStatusResponse PlatformApi::mds_status() {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("platform.mds_status", "GET", "/api/v1/mds/status",
                                            values, query, payload);

    return response.get<MdsStatusResponse>();
}

MdsRefreshOutcome PlatformApi::mds_refresh() {
    const std::vector<PathValue> values{};
    const std::vector<QueryValue> query{};
    const std::optional<nlohmann::json> payload = std::nullopt;
    const auto response = transport_->send("platform.mds_refresh", "POST", "/api/v1/mds/refresh",
                                            values, query, payload);

    return response.get<MdsRefreshOutcome>();
}

ManagementApi::ManagementApi(std::shared_ptr<Transport> transport, CallScope scope)
    : transport_(std::move(transport)), scope_(std::move(scope)) {}

OrganizationsApi ManagementApi::organizations() const {
    return OrganizationsApi(transport_, scope_);
}

TenantsApi ManagementApi::tenants() const {
    return TenantsApi(transport_, scope_);
}

UsersApi ManagementApi::users() const {
    return UsersApi(transport_, scope_);
}

GroupsApi ManagementApi::groups() const {
    return GroupsApi(transport_, scope_);
}

RolesApi ManagementApi::roles() const {
    return RolesApi(transport_, scope_);
}

PermissionsApi ManagementApi::permissions() const {
    return PermissionsApi(transport_, scope_);
}

ResourcesApi ManagementApi::resources() const {
    return ResourcesApi(transport_, scope_);
}

ScopesApi ManagementApi::scopes() const {
    return ScopesApi(transport_, scope_);
}

ServiceAccountsApi ManagementApi::service_accounts() const {
    return ServiceAccountsApi(transport_, scope_);
}

CertificatesApi ManagementApi::certificates() const {
    return CertificatesApi(transport_, scope_);
}

CaCertificatesApi ManagementApi::ca_certificates() const {
    return CaCertificatesApi(transport_, scope_);
}

PgpKeysApi ManagementApi::pgp_keys() const {
    return PgpKeysApi(transport_, scope_);
}

WebhooksApi ManagementApi::webhooks() const {
    return WebhooksApi(transport_, scope_);
}

Oauth2ClientsApi ManagementApi::oauth2_clients() const {
    return Oauth2ClientsApi(transport_, scope_);
}

FederationApi ManagementApi::federation() const {
    return FederationApi(transport_, scope_);
}

NotificationRulesApi ManagementApi::notification_rules() const {
    return NotificationRulesApi(transport_, scope_);
}

EmailConfigApi ManagementApi::email_config() const {
    return EmailConfigApi(transport_, scope_);
}

SettingsApi ManagementApi::settings() const {
    return SettingsApi(transport_, scope_);
}

ScimTokensApi ManagementApi::scim_tokens() const {
    return ScimTokensApi(transport_, scope_);
}

ReactorsApi ManagementApi::reactors() const {
    return ReactorsApi(transport_, scope_);
}

WebauthnPolicyApi ManagementApi::webauthn_policy() const {
    return WebauthnPolicyApi(transport_, scope_);
}

AuditApi ManagementApi::audit() const {
    return AuditApi(transport_, scope_);
}

PrivacyApi ManagementApi::privacy() const {
    return PrivacyApi(transport_, scope_);
}

PlatformApi ManagementApi::platform() const {
    return PlatformApi(transport_, scope_);
}

}  // namespace axiam::management

namespace axiam {

// The one place the §27 surface is attached to a Client. Defined here rather than in client.cpp
// so that translation unit keeps knowing nothing about the 146 generated operations.
management::ManagementApi Client::management() {
    p_->ensure_open();
    management::CallScope scope;
    return management::ManagementApi(std::make_shared<management::Transport>(p_), std::move(scope));
}

}  // namespace axiam
