// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.


#ifndef AXIAM_MANAGEMENT_HPP
#define AXIAM_MANAGEMENT_HPP

#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <vector>

#include "axiam/errors.hpp"
#include "axiam/management_models.hpp"

namespace axiam {
class Client;
}

namespace axiam::management {

/// One page's worth of `?offset=`/`?limit=`/`?search=` (§27.4 rule 4).
///
/// Default-constructed means the first page at the server's default size, unfiltered, which is
/// what a caller who does not care about paging gets by writing nothing.
struct PageRequest {
    std::int64_t offset = 0;   ///< How many items to skip; clamped at 0.
    std::int64_t limit = 50;   ///< How many to ask for; clamped to at least 1.

    /// A free-text filter applied by the SERVER, before `offset`/`limit`, or empty for none.
    ///
    /// Matched case-insensitively against the identifying fields of whatever is being listed --
    /// a name or username, plus the record id, so a UUID out of a log line can be pasted in
    /// as-is. `Page::total` then counts MATCHES, not rows, which is what lets a pager built on
    /// it show a page count belonging to the result set it is paging.
    ///
    /// It lives here, beside `offset` and `limit`, rather than as an extra argument on each of
    /// the twenty paginated `list` methods. That is what §27.4 rule 4 asks for and what makes
    /// `next()` -- and so `Page::next_request()` -- carry it across a whole walk: a walk that
    /// filtered its first request and dropped the term on the second would return the matches
    /// followed by the unfiltered tail, which reads as a server bug from the caller's side.
    ///
    /// An empty or all-whitespace term is the SAME request as none: no `search` parameter is
    /// sent at all. A search box that fires on every keystroke sends one the moment it is
    /// cleared, and "rows containing the empty string" is a different question from "all rows".
    /// The server caps the term's LENGTH and this SDK deliberately does not re-implement that
    /// cap, because a client-side truncation the server would not have made is a silently
    /// different query the caller has no way to see.
    std::string search;

    /// The page after this one -- same size and same term, advanced by exactly `limit`.
    ///
    /// By the requested limit, not by how many items came back: §27.4 rule 4 stops auto-paging
    /// on an EMPTY page, not a short one, and advancing by a short count would re-request rows
    /// the caller has already seen.
    PageRequest next() const;

    /// A COPY of this request filtered by `term`, leaving this one as it was.
    PageRequest matching(std::string term) const;

    /// The term as it goes on the wire, or empty when there is nothing to send.
    ///
    /// Trims, then treats a blank result as absent -- the same normalisation the server
    /// applies, and the reason absent and blank are the same request. Never truncates; see the
    /// note on `search`.
    static std::string normalize_search(const std::string& term);
};

/// One page of a paginated response (§27.4 rule 4).
///
/// `total` is the SERVER's count across every page. It is NOT `items.size()`, and deriving one
/// from the other is how a management tool silently processes the first fifty of four hundred
/// rows -- so they are separate members and neither is computed from the other.
///
/// A bare JSON array response is NOT a page and is never modelled as one; those operations
/// return a plain `std::vector`.
template <typename T>
struct Page {
    std::vector<T> items;     ///< The items on THIS page.
    std::int64_t total = 0;   ///< The server's total across all pages.
    PageRequest request;      ///< The request that produced this page.

    /// How many items are on THIS page. Deliberately not `total`.
    std::size_t size() const noexcept { return items.size(); }

    /// True when this page carried nothing -- §27.4 rule 4's stop condition.
    bool empty() const noexcept { return items.empty(); }

    auto begin() const noexcept { return items.begin(); }
    auto end() const noexcept { return items.end(); }

    /// The request that would fetch the page after this one.
    ///
    /// Carries this page's `search` term forward with it (§27.4 rule 4) -- that is
    /// `PageRequest::next()`'s job, so a walk written against `next_request()` filters every
    /// request of the walk rather than only its first.
    PageRequest next_request() const { return request.next(); }
};

/// `404 Not Found` on the management surface -- §27.4 rule 7.
///
/// Derives from AuthzError, which is not the obvious parent and is the point. AXIAM is
/// multi-tenant, and the server answers `404` for an object belonging to another tenant
/// PRECISELY SO a probing caller cannot tell "does not exist" from "exists, not yours".
/// Classifying it as an authorization outcome keeps the SDK from re-drawing a line the server
/// deliberately refused to draw.
///
/// A `catch (const AuthzError&)` written before §27 existed still catches it, which is exactly
/// the property the rule asks for -- and AuthzChallengeError already set that precedent here.
class NotFoundError : public AuthzError {
public:
    explicit NotFoundError(const std::string& message) : AuthzError(message) {}
};

/// `409 Conflict` on the management surface -- §27.4 rule 7.
///
/// Derives from AuthzError because §2 already maps `409` there as a resource-level refusal;
/// rule 7 KEEPS that mapping rather than moving it.
class ConflictError : public AuthzError {
public:
    explicit ConflictError(const std::string& message) : AuthzError(message) {}
};

/// `400`/`422` on the management surface -- §27.4 rule 7.
///
/// Derives from NetworkError, inherited from §2's own `400` row. That placement has one
/// consequence worth naming: §16 retries NetworkError, so without care a body the server has
/// already rejected would be sent three times. §27.4 rule 8 (only GET is retried) and an
/// explicit exclusion for this type are what stop it.
class ValidationError : public NetworkError {
public:
    explicit ValidationError(const std::string& message) : NetworkError(message) {}
};

/// Per-call override of the `{org_id}`/`{tenant_id}` a route substitutes (§27.4 rule 3).
///
/// Applied with a handle's `in_org()` / `for_tenant()`, which return a NEW handle rather than
/// mutating the one you called them on. An administrator holding a handle to their own tenant
/// should not find it repointed at someone else's because an unrelated code path re-scoped a
/// shared object -- and on a management surface that failure mode WRITES to the wrong tenant.
struct CallScope {
    std::optional<std::string> org_id;     ///< Overrides `{org_id}`.
    std::optional<std::string> tenant_id;  ///< Overrides `{tenant_id}`.
};

class Transport;    // defined in src/management_transport.hpp
class ManifestApi;  // defined in axiam/management_manifest.hpp

/// Organizations an SDK client may read and configure. Creation and deletion are outside the
/// SDK boundary (§27.0).
///
/// The `organizations` namespace handle (§27.2), reached as
/// `client.management().organizations()`. §27.3's C++ row is
/// `client.service_accounts().rotate_secret(id)` -- a method returning a handle, snake_case --
/// and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class OrganizationsApi {
public:
    OrganizationsApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    OrganizationsApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    OrganizationsApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/organizations`
    ///
    /// `GET /api/v1/organizations`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<Organization> list(const PageRequest& page = {});

    /// `GET /api/v1/organizations/{org_id}`
    ///
    /// `GET /api/v1/organizations/{org_id}`.
    Organization get();

    /// `PUT /api/v1/organizations/{org_id}`
    ///
    /// `PUT /api/v1/organizations/{org_id}`.
    ///
    /// @param body The request body.
    Organization update(const UpdateOrganizationRequest& body);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Tenants within an organization -- the isolation boundary every other namespace is scoped to.
///
/// The `tenants` namespace handle (§27.2), reached as `client.management().tenants()`. §27.3's
/// C++ row is `client.service_accounts().rotate_secret(id)` -- a method returning a handle,
/// snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class TenantsApi {
public:
    TenantsApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    TenantsApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    TenantsApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/organizations/{org_id}/tenants`
    ///
    /// `GET /api/v1/organizations/{org_id}/tenants`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<Tenant> list(const PageRequest& page = {});

    /// `POST /api/v1/organizations/{org_id}/tenants`
    ///
    /// `POST /api/v1/organizations/{org_id}/tenants`.
    ///
    /// @param body The request body.
    Tenant create(const CreateTenantRequest& body);

    /// `GET /api/v1/organizations/{org_id}/tenants/{tenant_id}`
    ///
    /// `GET /api/v1/organizations/{org_id}/tenants/{tenant_id}`.
    ///
    /// @param tenant_id The `{tenant_id}` path parameter.
    Tenant get(const std::string& tenant_id);

    /// `PUT /api/v1/organizations/{org_id}/tenants/{tenant_id}`
    ///
    /// `PUT /api/v1/organizations/{org_id}/tenants/{tenant_id}`.
    ///
    /// @param tenant_id The `{tenant_id}` path parameter.
    /// @param body The request body.
    Tenant update(const std::string& tenant_id, const UpdateTenant& body);

    /// `DELETE /api/v1/organizations/{org_id}/tenants/{tenant_id}`
    ///
    /// `DELETE /api/v1/organizations/{org_id}/tenants/{tenant_id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param tenant_id The `{tenant_id}` path parameter.
    void delete_(const std::string& tenant_id);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Users within the client's tenant, and the administrative side of their second factor and
/// lockout state.
///
/// The `users` namespace handle (§27.2), reached as `client.management().users()`. §27.3's C++
/// row is `client.service_accounts().rotate_secret(id)` -- a method returning a handle,
/// snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class UsersApi {
public:
    UsersApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    UsersApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    UsersApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/users`
    ///
    /// `GET /api/v1/users`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<UserResponse> list(const PageRequest& page = {});

    /// `POST /api/v1/users`
    ///
    /// `POST /api/v1/users`.
    ///
    /// @param body The request body.
    UserResponse create(const CreateUserRequest& body);

    /// `GET /api/v1/users/{user_id}`
    ///
    /// `GET /api/v1/users/{user_id}`.
    ///
    /// @param user_id The `{user_id}` path parameter.
    UserResponse get(const std::string& user_id);

    /// `PUT /api/v1/users/{user_id}`
    ///
    /// `PUT /api/v1/users/{user_id}`.
    ///
    /// @param user_id The `{user_id}` path parameter.
    /// @param body The request body.
    UserResponse update(const std::string& user_id, const UpdateUserRequest& body);

    /// `DELETE /api/v1/users/{user_id}`
    ///
    /// `DELETE /api/v1/users/{user_id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param user_id The `{user_id}` path parameter.
    void delete_(const std::string& user_id);

    /// `GET /api/v1/users/{user_id}/mfa-methods`
    ///
    /// `GET /api/v1/users/{user_id}/mfa-methods`.
    ///
    /// Returns the server's complete list. This endpoint is NOT paginated, so the result is a
    /// plain vector and never a Page (§27.4 rule 4).
    ///
    /// @param user_id The `{user_id}` path parameter.
    std::vector<MfaMethodResponse> list_mfa_methods(const std::string& user_id);

    /// `DELETE /api/v1/users/{user_id}/mfa-methods/{method_id}`
    ///
    /// `DELETE /api/v1/users/{user_id}/mfa-methods/{method_id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param user_id The `{user_id}` path parameter.
    /// @param method_id The `{method_id}` path parameter.
    void delete_mfa_method(const std::string& user_id, const std::string& method_id);

    /// `POST /api/v1/users/{user_id}/reset-mfa`
    ///
    /// `POST /api/v1/users/{user_id}/reset-mfa`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// @param user_id The `{user_id}` path parameter.
    void reset_mfa(const std::string& user_id);

    /// `POST /api/v1/users/{user_id}/unlock`
    ///
    /// `POST /api/v1/users/{user_id}/unlock`.
    ///
    /// @param user_id The `{user_id}` path parameter.
    UserResponse unlock(const std::string& user_id);

    /// `GET /api/v1/users/{user_id}/roles`
    ///
    /// `GET /api/v1/users/{user_id}/roles`.
    ///
    /// Returns the server's complete list. This endpoint is NOT paginated, so the result is a
    /// plain vector and never a Page (§27.4 rule 4).
    ///
    /// @param user_id The `{user_id}` path parameter.
    std::vector<RoleAssignment> list_roles(const std::string& user_id);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Named collections of users. Roles assigned to a group are inherited by every member.
///
/// The `groups` namespace handle (§27.2), reached as `client.management().groups()`. §27.3's
/// C++ row is `client.service_accounts().rotate_secret(id)` -- a method returning a handle,
/// snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class GroupsApi {
public:
    GroupsApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    GroupsApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    GroupsApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/groups`
    ///
    /// `GET /api/v1/groups`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<Group> list(const PageRequest& page = {});

    /// `POST /api/v1/groups`
    ///
    /// `POST /api/v1/groups`.
    ///
    /// @param body The request body.
    Group create(const CreateGroupRequest& body);

    /// `GET /api/v1/groups/{group_id}`
    ///
    /// `GET /api/v1/groups/{group_id}`.
    ///
    /// @param group_id The `{group_id}` path parameter.
    Group get(const std::string& group_id);

    /// `PUT /api/v1/groups/{group_id}`
    ///
    /// `PUT /api/v1/groups/{group_id}`.
    ///
    /// @param group_id The `{group_id}` path parameter.
    /// @param body The request body.
    Group update(const std::string& group_id, const UpdateGroup& body);

    /// `DELETE /api/v1/groups/{group_id}`
    ///
    /// `DELETE /api/v1/groups/{group_id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param group_id The `{group_id}` path parameter.
    void delete_(const std::string& group_id);

    /// `GET /api/v1/groups/{group_id}/members`
    ///
    /// `GET /api/v1/groups/{group_id}/members`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param group_id The `{group_id}` path parameter.
    /// @param page Which page to fetch; defaults to the first.
    Page<UserResponse> list_members(const std::string& group_id, const PageRequest& page = {});

    /// `POST /api/v1/groups/{group_id}/members`
    ///
    /// `POST /api/v1/groups/{group_id}/members`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// @param group_id The `{group_id}` path parameter.
    /// @param body The request body.
    void add_member(const std::string& group_id, const AddMemberRequest& body);

    /// `DELETE /api/v1/groups/{group_id}/members/{user_id}`
    ///
    /// `DELETE /api/v1/groups/{group_id}/members/{user_id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param group_id The `{group_id}` path parameter.
    /// @param user_id The `{user_id}` path parameter.
    void remove_member(const std::string& group_id, const std::string& user_id);

    /// `GET /api/v1/groups/{group_id}/roles`
    ///
    /// `GET /api/v1/groups/{group_id}/roles`.
    ///
    /// Returns the server's complete list. This endpoint is NOT paginated, so the result is a
    /// plain vector and never a Page (§27.4 rule 4).
    ///
    /// @param group_id The `{group_id}` path parameter.
    std::vector<RoleAssignment> list_roles(const std::string& group_id);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Roles, their permission sets, and their assignment to users and groups.
///
/// The `roles` namespace handle (§27.2), reached as `client.management().roles()`. §27.3's C++
/// row is `client.service_accounts().rotate_secret(id)` -- a method returning a handle,
/// snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class RolesApi {
public:
    RolesApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    RolesApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    RolesApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/roles`
    ///
    /// `GET /api/v1/roles`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<Role> list(const PageRequest& page = {});

    /// `POST /api/v1/roles`
    ///
    /// `POST /api/v1/roles`.
    ///
    /// @param body The request body.
    Role create(const CreateRoleRequest& body);

    /// `GET /api/v1/roles/{role_id}`
    ///
    /// `GET /api/v1/roles/{role_id}`.
    ///
    /// @param role_id The `{role_id}` path parameter.
    Role get(const std::string& role_id);

    /// `PUT /api/v1/roles/{role_id}`
    ///
    /// `PUT /api/v1/roles/{role_id}`.
    ///
    /// @param role_id The `{role_id}` path parameter.
    /// @param body The request body.
    Role update(const std::string& role_id, const UpdateRole& body);

    /// `DELETE /api/v1/roles/{role_id}`
    ///
    /// `DELETE /api/v1/roles/{role_id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param role_id The `{role_id}` path parameter.
    void delete_(const std::string& role_id);

    /// `GET /api/v1/roles/{role_id}/users`
    ///
    /// `GET /api/v1/roles/{role_id}/users`.
    ///
    /// Returns the server's complete list. This endpoint is NOT paginated, so the result is a
    /// plain vector and never a Page (§27.4 rule 4).
    ///
    /// @param role_id The `{role_id}` path parameter.
    std::vector<RoleUserAssignment> list_users(const std::string& role_id);

    /// `POST /api/v1/roles/{role_id}/users`
    ///
    /// `POST /api/v1/roles/{role_id}/users`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// @param role_id The `{role_id}` path parameter.
    /// @param body The request body.
    void assign_to_user(const std::string& role_id, const AssignRoleToUserRequest& body);

    /// `DELETE /api/v1/roles/{role_id}/users/{user_id}`
    ///
    /// `DELETE /api/v1/roles/{role_id}/users/{user_id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param role_id The `{role_id}` path parameter.
    /// @param user_id The `{user_id}` path parameter.
    /// @param resource_id The optional `resource_id` query parameter.
    void unassign_from_user(const std::string& role_id, const std::string& user_id, const std::optional<std::string>& resource_id = std::nullopt);

    /// `GET /api/v1/roles/{role_id}/groups`
    ///
    /// `GET /api/v1/roles/{role_id}/groups`.
    ///
    /// Returns the server's complete list. This endpoint is NOT paginated, so the result is a
    /// plain vector and never a Page (§27.4 rule 4).
    ///
    /// @param role_id The `{role_id}` path parameter.
    std::vector<RoleGroupAssignment> list_groups(const std::string& role_id);

    /// `POST /api/v1/roles/{role_id}/groups`
    ///
    /// `POST /api/v1/roles/{role_id}/groups`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// @param role_id The `{role_id}` path parameter.
    /// @param body The request body.
    void assign_to_group(const std::string& role_id, const AssignRoleToGroupRequest& body);

    /// `DELETE /api/v1/roles/{role_id}/groups/{group_id}`
    ///
    /// `DELETE /api/v1/roles/{role_id}/groups/{group_id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param role_id The `{role_id}` path parameter.
    /// @param group_id The `{group_id}` path parameter.
    /// @param resource_id The optional `resource_id` query parameter.
    void unassign_from_group(const std::string& role_id, const std::string& group_id, const std::optional<std::string>& resource_id = std::nullopt);

    /// `GET /api/v1/roles/{role_id}/permissions`
    ///
    /// `GET /api/v1/roles/{role_id}/permissions`.
    ///
    /// Returns the server's complete list. This endpoint is NOT paginated, so the result is a
    /// plain vector and never a Page (§27.4 rule 4).
    ///
    /// @param role_id The `{role_id}` path parameter.
    std::vector<ResolvedPermissionGrant> list_permissions(const std::string& role_id);

    /// `POST /api/v1/roles/{role_id}/permissions`
    ///
    /// `POST /api/v1/roles/{role_id}/permissions`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// @param role_id The `{role_id}` path parameter.
    /// @param body The request body.
    void grant_permission(const std::string& role_id, const GrantPermissionRequest& body);

    /// `DELETE /api/v1/roles/{role_id}/permissions/{permission_id}`
    ///
    /// `DELETE /api/v1/roles/{role_id}/permissions/{permission_id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param role_id The `{role_id}` path parameter.
    /// @param permission_id The `{permission_id}` path parameter.
    void revoke_permission(const std::string& role_id, const std::string& permission_id);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Permissions -- an action on a resource, optionally narrowed by a scope.
///
/// The `permissions` namespace handle (§27.2), reached as `client.management().permissions()`.
/// §27.3's C++ row is `client.service_accounts().rotate_secret(id)` -- a method returning a
/// handle, snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class PermissionsApi {
public:
    PermissionsApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    PermissionsApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    PermissionsApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/permissions`
    ///
    /// `GET /api/v1/permissions`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<Permission> list(const PageRequest& page = {});

    /// `POST /api/v1/permissions`
    ///
    /// `POST /api/v1/permissions`.
    ///
    /// @param body The request body.
    Permission create(const CreatePermissionRequest& body);

    /// `GET /api/v1/permissions/{permission_id}`
    ///
    /// `GET /api/v1/permissions/{permission_id}`.
    ///
    /// @param permission_id The `{permission_id}` path parameter.
    Permission get(const std::string& permission_id);

    /// `PUT /api/v1/permissions/{permission_id}`
    ///
    /// `PUT /api/v1/permissions/{permission_id}`.
    ///
    /// @param permission_id The `{permission_id}` path parameter.
    /// @param body The request body.
    Permission update(const std::string& permission_id, const UpdatePermissionRequest& body);

    /// `DELETE /api/v1/permissions/{permission_id}`
    ///
    /// `DELETE /api/v1/permissions/{permission_id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param permission_id The `{permission_id}` path parameter.
    void delete_(const std::string& permission_id);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// The resource hierarchy role assignments cascade down.
///
/// The `resources` namespace handle (§27.2), reached as `client.management().resources()`.
/// §27.3's C++ row is `client.service_accounts().rotate_secret(id)` -- a method returning a
/// handle, snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class ResourcesApi {
public:
    ResourcesApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    ResourcesApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    ResourcesApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/resources`
    ///
    /// `GET /api/v1/resources`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<Resource> list(const PageRequest& page = {});

    /// `POST /api/v1/resources`
    ///
    /// `POST /api/v1/resources`.
    ///
    /// @param body The request body.
    Resource create(const CreateResourceRequest& body);

    /// `GET /api/v1/resources/{resource_id}`
    ///
    /// `GET /api/v1/resources/{resource_id}`.
    ///
    /// @param resource_id The `{resource_id}` path parameter.
    Resource get(const std::string& resource_id);

    /// `PUT /api/v1/resources/{resource_id}`
    ///
    /// `PUT /api/v1/resources/{resource_id}`.
    ///
    /// @param resource_id The `{resource_id}` path parameter.
    /// @param body The request body.
    Resource update(const std::string& resource_id, const UpdateResourceRequest& body);

    /// `DELETE /api/v1/resources/{resource_id}`
    ///
    /// `DELETE /api/v1/resources/{resource_id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param resource_id The `{resource_id}` path parameter.
    void delete_(const std::string& resource_id);

    /// `GET /api/v1/resources/{resource_id}/children`
    ///
    /// `GET /api/v1/resources/{resource_id}/children`.
    ///
    /// Returns the server's complete list. This endpoint is NOT paginated, so the result is a
    /// plain vector and never a Page (§27.4 rule 4).
    ///
    /// @param resource_id The `{resource_id}` path parameter.
    std::vector<Resource> list_children(const std::string& resource_id);

    /// `GET /api/v1/resources/{resource_id}/ancestors`
    ///
    /// `GET /api/v1/resources/{resource_id}/ancestors`.
    ///
    /// Returns the server's complete list. This endpoint is NOT paginated, so the result is a
    /// plain vector and never a Page (§27.4 rule 4).
    ///
    /// @param resource_id The `{resource_id}` path parameter.
    std::vector<Resource> list_ancestors(const std::string& resource_id);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Sub-resource granularity, always addressed under their resource.
///
/// The `scopes` namespace handle (§27.2), reached as `client.management().scopes()`. §27.3's
/// C++ row is `client.service_accounts().rotate_secret(id)` -- a method returning a handle,
/// snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class ScopesApi {
public:
    ScopesApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    ScopesApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    ScopesApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/resources/{resource_id}/scopes`
    ///
    /// `GET /api/v1/resources/{resource_id}/scopes`.
    ///
    /// Returns the server's complete list. This endpoint is NOT paginated, so the result is a
    /// plain vector and never a Page (§27.4 rule 4).
    ///
    /// @param resource_id The `{resource_id}` path parameter.
    std::vector<Scope> list(const std::string& resource_id);

    /// `POST /api/v1/resources/{resource_id}/scopes`
    ///
    /// `POST /api/v1/resources/{resource_id}/scopes`.
    ///
    /// @param resource_id The `{resource_id}` path parameter.
    /// @param body The request body.
    Scope create(const std::string& resource_id, const CreateScopeRequest& body);

    /// `GET /api/v1/resources/{resource_id}/scopes/{scope_id}`
    ///
    /// `GET /api/v1/resources/{resource_id}/scopes/{scope_id}`.
    ///
    /// @param resource_id The `{resource_id}` path parameter.
    /// @param scope_id The `{scope_id}` path parameter.
    Scope get(const std::string& resource_id, const std::string& scope_id);

    /// `PUT /api/v1/resources/{resource_id}/scopes/{scope_id}`
    ///
    /// `PUT /api/v1/resources/{resource_id}/scopes/{scope_id}`.
    ///
    /// @param resource_id The `{resource_id}` path parameter.
    /// @param scope_id The `{scope_id}` path parameter.
    /// @param body The request body.
    Scope update(const std::string& resource_id, const std::string& scope_id, const UpdateScopeRequest& body);

    /// `DELETE /api/v1/resources/{resource_id}/scopes/{scope_id}`
    ///
    /// `DELETE /api/v1/resources/{resource_id}/scopes/{scope_id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param resource_id The `{resource_id}` path parameter.
    /// @param scope_id The `{scope_id}` path parameter.
    void delete_(const std::string& resource_id, const std::string& scope_id);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Machine identities, their secrets, and the certificate a device-bound one authenticates
/// with.
///
/// The `service_accounts` namespace handle (§27.2), reached as
/// `client.management().service_accounts()`. §27.3's C++ row is
/// `client.service_accounts().rotate_secret(id)` -- a method returning a handle, snake_case --
/// and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class ServiceAccountsApi {
public:
    ServiceAccountsApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    ServiceAccountsApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    ServiceAccountsApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/service-accounts`
    ///
    /// `GET /api/v1/service-accounts`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<ServiceAccountResponse> list(const PageRequest& page = {});

    /// `POST /api/v1/service-accounts`
    ///
    /// `POST /api/v1/service-accounts`.
    ///
    /// The response carries a ONE-TIME secret (`client_secret`): the server will not return it
    /// again, so a caller that does not persist it here cannot recover it (§27.5).
    ///
    /// @param body The request body.
    ServiceAccountCreatedResponse create(const CreateServiceAccountRequest& body);

    /// `GET /api/v1/service-accounts/{sa_id}`
    ///
    /// `GET /api/v1/service-accounts/{sa_id}`.
    ///
    /// @param sa_id The `{sa_id}` path parameter.
    ServiceAccountResponse get(const std::string& sa_id);

    /// `PUT /api/v1/service-accounts/{sa_id}`
    ///
    /// `PUT /api/v1/service-accounts/{sa_id}`.
    ///
    /// @param sa_id The `{sa_id}` path parameter.
    /// @param body The request body.
    ServiceAccountResponse update(const std::string& sa_id, const UpdateServiceAccount& body);

    /// `DELETE /api/v1/service-accounts/{sa_id}`
    ///
    /// `DELETE /api/v1/service-accounts/{sa_id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param sa_id The `{sa_id}` path parameter.
    void delete_(const std::string& sa_id);

    /// `POST /api/v1/service-accounts/{sa_id}/rotate-secret`
    ///
    /// `POST /api/v1/service-accounts/{sa_id}/rotate-secret`.
    ///
    /// The response carries a ONE-TIME secret (`client_secret`): the server will not return it
    /// again, so a caller that does not persist it here cannot recover it (§27.5).
    ///
    /// @param sa_id The `{sa_id}` path parameter.
    RotateSecretResponse rotate_secret(const std::string& sa_id);

    /// `POST /api/v1/service-accounts/{sa_id}/bind-certificate`
    ///
    /// `POST /api/v1/service-accounts/{sa_id}/bind-certificate`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// @param sa_id The `{sa_id}` path parameter.
    /// @param body The request body.
    void bind_certificate(const std::string& sa_id, const BindCertificate& body);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// End-entity X.509 certificates -- the ones issued to users, services and IoT devices.
///
/// The `certificates` namespace handle (§27.2), reached as
/// `client.management().certificates()`. §27.3's C++ row is
/// `client.service_accounts().rotate_secret(id)` -- a method returning a handle, snake_case --
/// and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class CertificatesApi {
public:
    CertificatesApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    CertificatesApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    CertificatesApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/certificates`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<Certificate> list(const PageRequest& page = {});

    /// `POST /api/v1/certificates`
    ///
    /// `POST /api/v1/certificates`.
    ///
    /// The response carries a ONE-TIME secret (`private_key_pem`): the server will not return
    /// it again, so a caller that does not persist it here cannot recover it (§27.5).
    ///
    /// @param body The request body.
    GeneratedCertificate generate(const CreateCertificateRequest& body);

    /// `GET /api/v1/certificates/{id}`
    ///
    /// `GET /api/v1/certificates/{id}`.
    ///
    /// @param id The `{id}` path parameter.
    Certificate get(const std::string& id);

    /// `POST /api/v1/certificates/{id}/revoke`
    ///
    /// `POST /api/v1/certificates/{id}/revoke`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// @param id The `{id}` path parameter.
    void revoke(const std::string& id);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Organization CAs and the per-tenant signing CAs chained beneath them.
///
/// The `ca_certificates` namespace handle (§27.2), reached as
/// `client.management().ca_certificates()`. §27.3's C++ row is
/// `client.service_accounts().rotate_secret(id)` -- a method returning a handle, snake_case --
/// and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class CaCertificatesApi {
public:
    CaCertificatesApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    CaCertificatesApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    CaCertificatesApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/organizations/{org_id}/ca-certificates`
    ///
    /// `GET /api/v1/organizations/{org_id}/ca-certificates`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<CaCertificate> list(const PageRequest& page = {});

    /// `POST /api/v1/organizations/{org_id}/ca-certificates`
    ///
    /// `POST /api/v1/organizations/{org_id}/ca-certificates`.
    ///
    /// The response carries a ONE-TIME secret (`private_key_pem`): the server will not return
    /// it again, so a caller that does not persist it here cannot recover it (§27.5).
    ///
    /// @param body The request body.
    GeneratedCaCertificate generate(const CreateCaCertificateRequest& body);

    /// `POST /api/v1/organizations/{org_id}/ca-certificates/import`
    ///
    /// `POST /api/v1/organizations/{org_id}/ca-certificates/import`.
    ///
    /// @param body The request body.
    CaCertificate import_ca(const ImportCaCertificateRequest& body);

    /// `GET /api/v1/organizations/{org_id}/ca-certificates/{id}`
    ///
    /// `GET /api/v1/organizations/{org_id}/ca-certificates/{id}`.
    ///
    /// @param id The `{id}` path parameter.
    CaCertificate get(const std::string& id);

    /// `POST /api/v1/organizations/{org_id}/ca-certificates/{id}/revoke`
    ///
    /// `POST /api/v1/organizations/{org_id}/ca-certificates/{id}/revoke`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// @param id The `{id}` path parameter.
    void revoke(const std::string& id);

    /// `POST /api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody`
    ///
    /// `POST /api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody`.
    ///
    /// @param id The `{id}` path parameter.
    MigrateCustodyResponse migrate_custody(const std::string& id);

    /// `PUT /api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor`
    ///
    /// `PUT /api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor`.
    ///
    /// @param id The `{id}` path parameter.
    /// @param body The request body.
    MtlsTrustAnchorResponse set_mtls_trust_anchor(const std::string& id, const SetMtlsTrustAnchor& body);

    /// `GET /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas`
    ///
    /// `GET /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param tenant_id The `{tenant_id}` path parameter.
    /// @param page Which page to fetch; defaults to the first.
    Page<CaCertificate> list_signing_cas(const std::string& tenant_id, const PageRequest& page = {});

    /// `POST /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas`
    ///
    /// `POST /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas`.
    ///
    /// The response carries a ONE-TIME secret (`private_key_pem`): the server will not return
    /// it again, so a caller that does not persist it here cannot recover it (§27.5).
    ///
    /// @param tenant_id The `{tenant_id}` path parameter.
    /// @param body The request body.
    GeneratedCaCertificate generate_signing_ca(const std::string& tenant_id, const CreateIntermediateCaRequest& body);

    /// `POST /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr`
    ///
    /// `POST /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr`.
    ///
    /// @param tenant_id The `{tenant_id}` path parameter.
    /// @param body The request body.
    CaCertificate sign_signing_ca_csr(const std::string& tenant_id, const SignIntermediateCsrRequest& body);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// OpenPGP keys used for audit signing and encrypted data export.
///
/// The `pgp_keys` namespace handle (§27.2), reached as `client.management().pgp_keys()`.
/// §27.3's C++ row is `client.service_accounts().rotate_secret(id)` -- a method returning a
/// handle, snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class PgpKeysApi {
public:
    PgpKeysApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    PgpKeysApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    PgpKeysApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/pgp-keys`
    ///
    /// `GET /api/v1/pgp-keys`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<PgpKey> list(const PageRequest& page = {});

    /// `POST /api/v1/pgp-keys`
    ///
    /// `POST /api/v1/pgp-keys`.
    ///
    /// The response carries a ONE-TIME secret (`private_key_armored`): the server will not
    /// return it again, so a caller that does not persist it here cannot recover it (§27.5).
    ///
    /// @param body The request body.
    GeneratedPgpKey generate(const CreatePgpKeyRequest& body);

    /// `GET /api/v1/pgp-keys/{id}`
    ///
    /// `GET /api/v1/pgp-keys/{id}`.
    ///
    /// @param id The `{id}` path parameter.
    PgpKey get(const std::string& id);

    /// `POST /api/v1/pgp-keys/{id}/revoke`
    ///
    /// `POST /api/v1/pgp-keys/{id}/revoke`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// @param id The `{id}` path parameter.
    void revoke(const std::string& id);

    /// `POST /api/v1/pgp-keys/{id}/encrypt`
    ///
    /// `POST /api/v1/pgp-keys/{id}/encrypt`.
    ///
    /// @param id The `{id}` path parameter.
    /// @param body The request body.
    EncryptedExport encrypt(const std::string& id, const EncryptRequest& body);

    /// `POST /api/v1/pgp-keys/sign-audit-batch`
    ///
    /// `POST /api/v1/pgp-keys/sign-audit-batch`.
    ///
    /// @param body The request body.
    SignedAuditBatch sign_audit_batch(const SignAuditBatchRequest& body);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Outbound event notifications. Delivery signatures are verified with the §13 helper, which
/// this namespace configures.
///
/// The `webhooks` namespace handle (§27.2), reached as `client.management().webhooks()`.
/// §27.3's C++ row is `client.service_accounts().rotate_secret(id)` -- a method returning a
/// handle, snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class WebhooksApi {
public:
    WebhooksApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    WebhooksApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    WebhooksApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/webhooks`
    ///
    /// `GET /api/v1/webhooks`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<WebhookResponse> list(const PageRequest& page = {});

    /// `POST /api/v1/webhooks`
    ///
    /// `POST /api/v1/webhooks`.
    ///
    /// @param body The request body.
    WebhookResponse create(const CreateWebhookRequest& body);

    /// `GET /api/v1/webhooks/{id}`
    ///
    /// `GET /api/v1/webhooks/{id}`.
    ///
    /// @param id The `{id}` path parameter.
    WebhookResponse get(const std::string& id);

    /// `PUT /api/v1/webhooks/{id}`
    ///
    /// `PUT /api/v1/webhooks/{id}`.
    ///
    /// @param id The `{id}` path parameter.
    /// @param body The request body.
    WebhookResponse update(const std::string& id, const UpdateWebhookRequest& body);

    /// `DELETE /api/v1/webhooks/{id}`
    ///
    /// `DELETE /api/v1/webhooks/{id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param id The `{id}` path parameter.
    void delete_(const std::string& id);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Registered OAuth2/OIDC clients -- the registration half of what §12, §21 and §26 then speak
/// to.
///
/// The `oauth2_clients` namespace handle (§27.2), reached as
/// `client.management().oauth2_clients()`. §27.3's C++ row is
/// `client.service_accounts().rotate_secret(id)` -- a method returning a handle, snake_case --
/// and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class Oauth2ClientsApi {
public:
    Oauth2ClientsApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    Oauth2ClientsApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    Oauth2ClientsApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/oauth2-clients`
    ///
    /// `GET /api/v1/oauth2-clients`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<OAuth2ClientResponse> list(const PageRequest& page = {});

    /// `POST /api/v1/oauth2-clients`
    ///
    /// `POST /api/v1/oauth2-clients`.
    ///
    /// The response carries a ONE-TIME secret (`client_secret`): the server will not return it
    /// again, so a caller that does not persist it here cannot recover it (§27.5).
    ///
    /// @param body The request body.
    OAuth2ClientCreatedResponse create(const CreateOAuth2ClientRequest& body);

    /// `GET /api/v1/oauth2-clients/{id}`
    ///
    /// `GET /api/v1/oauth2-clients/{id}`.
    ///
    /// @param id The `{id}` path parameter.
    OAuth2ClientResponse get(const std::string& id);

    /// `PUT /api/v1/oauth2-clients/{id}`
    ///
    /// `PUT /api/v1/oauth2-clients/{id}`.
    ///
    /// @param id The `{id}` path parameter.
    /// @param body The request body.
    OAuth2ClientResponse update(const std::string& id, const UpdateOAuth2ClientRequest& body);

    /// `DELETE /api/v1/oauth2-clients/{id}`
    ///
    /// `DELETE /api/v1/oauth2-clients/{id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param id The `{id}` path parameter.
    void delete_(const std::string& id);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Upstream IdP configuration and the per-user links it produces.
///
/// The `federation` namespace handle (§27.2), reached as `client.management().federation()`.
/// §27.3's C++ row is `client.service_accounts().rotate_secret(id)` -- a method returning a
/// handle, snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class FederationApi {
public:
    FederationApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    FederationApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    FederationApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/federation-configs`
    ///
    /// `GET /api/v1/federation-configs`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<FederationConfigResponse> list_configs(const PageRequest& page = {});

    /// `POST /api/v1/federation-configs`
    ///
    /// `POST /api/v1/federation-configs`.
    ///
    /// @param body The request body.
    FederationConfigResponse create_config(const CreateFederationConfigRequest& body);

    /// `GET /api/v1/federation-configs/{id}`
    ///
    /// `GET /api/v1/federation-configs/{id}`.
    ///
    /// @param id The `{id}` path parameter.
    FederationConfigResponse get_config(const std::string& id);

    /// `PUT /api/v1/federation-configs/{id}`
    ///
    /// `PUT /api/v1/federation-configs/{id}`.
    ///
    /// @param id The `{id}` path parameter.
    /// @param body The request body.
    FederationConfigResponse update_config(const std::string& id, const UpdateFederationConfigRequest& body);

    /// `DELETE /api/v1/federation-configs/{id}`
    ///
    /// `DELETE /api/v1/federation-configs/{id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param id The `{id}` path parameter.
    void delete_config(const std::string& id);

    /// `GET /api/v1/federation-links/user/{user_id}`
    ///
    /// `GET /api/v1/federation-links/user/{user_id}`.
    ///
    /// Returns the server's complete list. This endpoint is NOT paginated, so the result is a
    /// plain vector and never a Page (§27.4 rule 4).
    ///
    /// @param user_id The `{user_id}` path parameter.
    std::vector<FederationLinkResponse> list_user_links(const std::string& user_id);

    /// `DELETE /api/v1/federation-links/{id}`
    ///
    /// `DELETE /api/v1/federation-links/{id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param id The `{id}` path parameter.
    void delete_link(const std::string& id);

    /// `POST /api/v1/federation/oidc/authorize`
    ///
    /// `POST /api/v1/federation/oidc/authorize`.
    ///
    /// @param body The request body.
    OidcAuthorizeResponse oidc_authorize(const OidcAuthorizeRequest& body);

    /// `POST /api/v1/federation/oidc/callback`
    ///
    /// `POST /api/v1/federation/oidc/callback`.
    ///
    /// @param body The request body.
    OidcCallbackResponse oidc_callback(const OidcCallbackRequest& body);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Which events raise a notification, and to whom.
///
/// The `notification_rules` namespace handle (§27.2), reached as
/// `client.management().notification_rules()`. §27.3's C++ row is
/// `client.service_accounts().rotate_secret(id)` -- a method returning a handle, snake_case --
/// and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class NotificationRulesApi {
public:
    NotificationRulesApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    NotificationRulesApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    NotificationRulesApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/notification-rules`
    ///
    /// `GET /api/v1/notification-rules`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<NotificationRuleResponse> list(const PageRequest& page = {});

    /// `POST /api/v1/notification-rules`
    ///
    /// `POST /api/v1/notification-rules`.
    ///
    /// @param body The request body.
    NotificationRuleResponse create(const CreateNotificationRuleRequest& body);

    /// `GET /api/v1/notification-rules/{id}`
    ///
    /// `GET /api/v1/notification-rules/{id}`.
    ///
    /// @param id The `{id}` path parameter.
    NotificationRuleResponse get(const std::string& id);

    /// `PUT /api/v1/notification-rules/{id}`
    ///
    /// `PUT /api/v1/notification-rules/{id}`.
    ///
    /// @param id The `{id}` path parameter.
    /// @param body The request body.
    NotificationRuleResponse update(const std::string& id, const UpdateNotificationRuleRequest& body);

    /// `DELETE /api/v1/notification-rules/{id}`
    ///
    /// `DELETE /api/v1/notification-rules/{id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param id The `{id}` path parameter.
    void delete_(const std::string& id);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Transactional-mail transport, configurable at organization level and overridable per tenant.
///
/// The `email_config` namespace handle (§27.2), reached as
/// `client.management().email_config()`. §27.3's C++ row is
/// `client.service_accounts().rotate_secret(id)` -- a method returning a handle, snake_case --
/// and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class EmailConfigApi {
public:
    EmailConfigApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    EmailConfigApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    EmailConfigApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/organizations/{org_id}/email-config`
    ///
    /// `GET /api/v1/organizations/{org_id}/email-config`.
    EmailConfig get_org();

    /// `PUT /api/v1/organizations/{org_id}/email-config`
    ///
    /// `PUT /api/v1/organizations/{org_id}/email-config`.
    ///
    /// @param body The request body.
    EmailConfig set_org(const SetOrgEmailConfig& body);

    /// `DELETE /api/v1/organizations/{org_id}/email-config`
    ///
    /// `DELETE /api/v1/organizations/{org_id}/email-config`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    void delete_org();

    /// `POST /api/v1/organizations/{org_id}/email-config/test`
    ///
    /// `POST /api/v1/organizations/{org_id}/email-config/test`.
    EmailTestResult test_org();

    /// `GET /api/v1/tenants/{tenant_id}/email-config`
    ///
    /// `GET /api/v1/tenants/{tenant_id}/email-config`.
    EmailConfigOverride get_tenant();

    /// `PUT /api/v1/tenants/{tenant_id}/email-config`
    ///
    /// `PUT /api/v1/tenants/{tenant_id}/email-config`.
    ///
    /// @param body The request body.
    EmailConfigOverride set_tenant(const EmailConfigOverride& body);

    /// `DELETE /api/v1/tenants/{tenant_id}/email-config`
    ///
    /// `DELETE /api/v1/tenants/{tenant_id}/email-config`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    void delete_tenant();

    /// `POST /api/v1/tenants/{tenant_id}/email-config/test`
    ///
    /// `POST /api/v1/tenants/{tenant_id}/email-config/test`.
    EmailTestResult test_tenant();

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Effective settings, and the organization/tenant layers they resolve from.
///
/// The `settings` namespace handle (§27.2), reached as `client.management().settings()`.
/// §27.3's C++ row is `client.service_accounts().rotate_secret(id)` -- a method returning a
/// handle, snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class SettingsApi {
public:
    SettingsApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    SettingsApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    SettingsApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/organizations/{org_id}/settings`
    ///
    /// `GET /api/v1/organizations/{org_id}/settings`.
    SecuritySettings get_org();

    /// `PUT /api/v1/organizations/{org_id}/settings`
    ///
    /// `PUT /api/v1/organizations/{org_id}/settings`.
    ///
    /// @param body The request body.
    SecuritySettings set_org(const SetOrgSettings& body);

    /// `GET /api/v1/settings`
    ///
    /// `GET /api/v1/settings`.
    SecuritySettings get_effective();

    /// `PUT /api/v1/settings`
    ///
    /// `PUT /api/v1/settings`.
    ///
    /// @param body The request body.
    SecuritySettings set_effective(const TenantSettingsOverride& body);

    /// `GET /api/v1/tenants/{tenant_id}/settings`
    ///
    /// `GET /api/v1/tenants/{tenant_id}/settings`.
    TenantSettingsOverride get_tenant_override();

    /// `PUT /api/v1/tenants/{tenant_id}/settings`
    ///
    /// `PUT /api/v1/tenants/{tenant_id}/settings`.
    ///
    /// @param body The request body.
    TenantSettingsOverride set_tenant_override(const TenantSettingsOverride& body);

    /// `DELETE /api/v1/tenants/{tenant_id}/settings`
    ///
    /// `DELETE /api/v1/tenants/{tenant_id}/settings`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    void delete_tenant_override();

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Bearer tokens for the SCIM 2.0 provisioning endpoint.
///
/// The `scim_tokens` namespace handle (§27.2), reached as `client.management().scim_tokens()`.
/// §27.3's C++ row is `client.service_accounts().rotate_secret(id)` -- a method returning a
/// handle, snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class ScimTokensApi {
public:
    ScimTokensApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    ScimTokensApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    ScimTokensApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/scim-tokens`
    ///
    /// `GET /api/v1/scim-tokens`.
    ///
    /// Returns the server's complete list. This endpoint is NOT paginated, so the result is a
    /// plain vector and never a Page (§27.4 rule 4).
    std::vector<ScimTokenResponse> list();

    /// `POST /api/v1/scim-tokens`
    ///
    /// `POST /api/v1/scim-tokens`.
    ///
    /// The response carries a ONE-TIME secret (`provisioning_token`): the server will not
    /// return it again, so a caller that does not persist it here cannot recover it (§27.5).
    ///
    /// @param body The request body.
    CreateScimTokenResponse create(const CreateScimTokenRequest& body);

    /// `DELETE /api/v1/scim-tokens/{id}`
    ///
    /// `DELETE /api/v1/scim-tokens/{id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param id The `{id}` path parameter.
    void revoke(const std::string& id);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Registration of §22 AMQP extension actors -- the admin surface §22.9 describes, which no SDK
/// could previously reach.
///
/// The `reactors` namespace handle (§27.2), reached as `client.management().reactors()`.
/// §27.3's C++ row is `client.service_accounts().rotate_secret(id)` -- a method returning a
/// handle, snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class ReactorsApi {
public:
    ReactorsApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    ReactorsApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    ReactorsApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/reactors`
    ///
    /// `GET /api/v1/reactors`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    Page<ReactorResponse> list(const PageRequest& page = {});

    /// `POST /api/v1/reactors`
    ///
    /// `POST /api/v1/reactors`.
    ///
    /// @param body The request body.
    ReactorResponse create(const CreateReactorRequest& body);

    /// `GET /api/v1/reactors/{id}`
    ///
    /// `GET /api/v1/reactors/{id}`.
    ///
    /// @param id The `{id}` path parameter.
    ReactorResponse get(const std::string& id);

    /// `PUT /api/v1/reactors/{id}`
    ///
    /// `PUT /api/v1/reactors/{id}`.
    ///
    /// @param id The `{id}` path parameter.
    /// @param body The request body.
    ReactorResponse update(const std::string& id, const UpdateReactorRequest& body);

    /// `DELETE /api/v1/reactors/{id}`
    ///
    /// `DELETE /api/v1/reactors/{id}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// NOT idempotent (§27.4 rule 6): deleting something already deleted throws NotFoundError
    /// rather than succeeding quietly.
    ///
    /// @param id The `{id}` path parameter.
    void delete_(const std::string& id);

    /// `GET /api/v1/reactors/events` — the registry, verbatim.
    ///
    /// `GET /api/v1/reactors/events`.
    ///
    /// Returns the server's complete list. This endpoint is NOT paginated, so the result is a
    /// plain vector and never a Page (§27.4 rule 4).
    std::vector<ReactorEventDescriptor> list_events();

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Per-tenant attestation policy governing the §24 ceremonies, and the compliance report over
/// it.
///
/// The `webauthn_policy` namespace handle (§27.2), reached as
/// `client.management().webauthn_policy()`. §27.3's C++ row is
/// `client.service_accounts().rotate_secret(id)` -- a method returning a handle, snake_case --
/// and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class WebauthnPolicyApi {
public:
    WebauthnPolicyApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    WebauthnPolicyApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    WebauthnPolicyApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/tenants/{tenant_id}/webauthn/attestation-policy`
    ///
    /// `GET /api/v1/tenants/{tenant_id}/webauthn/attestation-policy`.
    PolicyResponse get();

    /// `PUT /api/v1/tenants/{tenant_id}/webauthn/attestation-policy`
    ///
    /// `PUT /api/v1/tenants/{tenant_id}/webauthn/attestation-policy`.
    ///
    /// @param body The request body.
    WebauthnAttestationPolicy set(const WebauthnAttestationPolicy& body);

    /// `GET /api/v1/tenants/{tenant_id}/webauthn/compliance-report`
    ///
    /// `GET /api/v1/tenants/{tenant_id}/webauthn/compliance-report`.
    ///
    /// Returns the server's complete list. This endpoint is NOT paginated, so the result is a
    /// plain vector and never a Page (§27.4 rule 4).
    std::vector<ComplianceReportEntry> compliance_report();

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Append-only audit log, read-only by construction.
///
/// The `audit` namespace handle (§27.2), reached as `client.management().audit()`. §27.3's C++
/// row is `client.service_accounts().rotate_secret(id)` -- a method returning a handle,
/// snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class AuditApi {
public:
    AuditApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    AuditApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    AuditApi for_tenant(std::string tenant_id) const;

    /// `GET /api/v1/audit-logs`
    ///
    /// `GET /api/v1/audit-logs`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    /// @param actor_id The optional `actor_id` query parameter.
    /// @param action The optional `action` query parameter.
    /// @param outcome The optional `outcome` query parameter.
    /// @param resource_id The optional `resource_id` query parameter.
    /// @param from The optional `from` query parameter.
    /// @param to The optional `to` query parameter.
    Page<AuditLogEntry> list(const PageRequest& page = {}, const std::optional<std::string>& actor_id = std::nullopt, const std::optional<std::string>& action = std::nullopt, const std::optional<std::string>& outcome = std::nullopt, const std::optional<std::string>& resource_id = std::nullopt, const std::optional<std::string>& from = std::nullopt, const std::optional<std::string>& to = std::nullopt);

    /// `GET /api/v1/audit-logs/system`
    ///
    /// `GET /api/v1/audit-logs/system`.
    ///
    /// Returns ONE page. `Page::total` is the server's count across all pages and is not
    /// `items.size()` -- see §27.4 rule 4.
    ///
    /// @param page Which page to fetch; defaults to the first.
    /// @param actor_id The optional `actor_id` query parameter.
    /// @param action The optional `action` query parameter.
    /// @param outcome The optional `outcome` query parameter.
    /// @param resource_id The optional `resource_id` query parameter.
    /// @param from The optional `from` query parameter.
    /// @param to The optional `to` query parameter.
    Page<AuditLogEntry> list_system(const PageRequest& page = {}, const std::optional<std::string>& actor_id = std::nullopt, const std::optional<std::string>& action = std::nullopt, const std::optional<std::string>& outcome = std::nullopt, const std::optional<std::string>& resource_id = std::nullopt, const std::optional<std::string>& from = std::nullopt, const std::optional<std::string>& to = std::nullopt);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// GDPR self-service: the authenticated account's own export and erasure. Scoped to the caller,
/// never to another user.
///
/// The `privacy` namespace handle (§27.2), reached as `client.management().privacy()`. §27.3's
/// C++ row is `client.service_accounts().rotate_secret(id)` -- a method returning a handle,
/// snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class PrivacyApi {
public:
    PrivacyApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    PrivacyApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    PrivacyApi for_tenant(std::string tenant_id) const;

    /// `POST /api/v1/account/export`
    ///
    /// `POST /api/v1/account/export`.
    ///
    /// Returns nothing; the server answers with an empty body.
    void request_export();

    /// `GET /api/v1/account/export/{token}`
    ///
    /// `GET /api/v1/account/export/{token}`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// @param token The `{token}` path parameter.
    void download_export(const std::string& token);

    /// `POST /api/v1/account/delete`
    ///
    /// `POST /api/v1/account/delete`.
    ///
    /// Returns nothing; the server answers with an empty body.
    void request_delete();

    /// `GET /api/v1/auth/account/delete/cancel?token=<opaque>`
    ///
    /// `GET /api/v1/auth/account/delete/cancel`.
    ///
    /// Returns nothing; the server answers with an empty body.
    ///
    /// @param token The required `token` query parameter.
    void cancel_delete(const std::string& token);

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// Deployment-level probes and FIDO metadata state. Unauthenticated where the server leaves
/// them so.
///
/// The `platform` namespace handle (§27.2), reached as `client.management().platform()`.
/// §27.3's C++ row is `client.service_accounts().rotate_secret(id)` -- a method returning a
/// handle, snake_case -- and that is what this is.
///
/// Every method goes through the one shared transport, so §3 CSRF, the §4 cookie jar, the §5
/// tenant header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything
/// to opt in (§27.8).
class PlatformApi {
public:
    PlatformApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// A COPY of this handle scoped to `org_id` (§27.4 rule 3). Returns a new handle; the one
    /// you called it on is untouched.
    PlatformApi in_org(std::string org_id) const;

    /// A COPY of this handle scoped to `tenant_id` (§27.4 rule 3). See in_org().
    PlatformApi for_tenant(std::string tenant_id) const;

    /// `GET /health` — liveness probe. Always returns 200.
    ///
    /// `GET /health`.
    HealthResponse health();

    /// `GET /ready` — readiness probe. Checks DB connectivity.
    ///
    /// `GET /ready`.
    ReadyResponse ready();

    /// `GET /api/v1/mds/status`
    ///
    /// `GET /api/v1/mds/status`.
    MdsStatusResponse mds_status();

    /// `POST /api/v1/mds/refresh`
    ///
    /// `POST /api/v1/mds/refresh`.
    MdsRefreshOutcome mds_refresh();

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

/// The CONTRACT.md §27 management surface: 146 operations across 24 namespaces.
///
/// Reached as `client.management()`. Each accessor hands back a namespace handle (§27.2) that
/// can be re-scoped per call with `in_org()` / `for_tenant()`.
///
/// Handles are constructed on demand rather than cached. §27.4 rule 10 forbids caching
/// RESPONSES, not handles -- but a handle is a shared pointer and a scope, and building one per
/// call keeps `in_org()` from having anything shared to mutate.
class ManagementApi {
public:
    explicit ManagementApi(std::shared_ptr<Transport> transport, CallScope scope);

    /// Organizations an SDK client may read and configure. Creation and deletion are outside
    /// the SDK boundary (§27.0).
    OrganizationsApi organizations() const;

    /// Tenants within an organization -- the isolation boundary every other namespace is scoped
    /// to.
    TenantsApi tenants() const;

    /// Users within the client's tenant, and the administrative side of their second factor and
    /// lockout state.
    UsersApi users() const;

    /// Named collections of users. Roles assigned to a group are inherited by every member.
    GroupsApi groups() const;

    /// Roles, their permission sets, and their assignment to users and groups.
    RolesApi roles() const;

    /// Permissions -- an action on a resource, optionally narrowed by a scope.
    PermissionsApi permissions() const;

    /// The resource hierarchy role assignments cascade down.
    ResourcesApi resources() const;

    /// Sub-resource granularity, always addressed under their resource.
    ScopesApi scopes() const;

    /// Machine identities, their secrets, and the certificate a device-bound one authenticates
    /// with.
    ServiceAccountsApi service_accounts() const;

    /// End-entity X.509 certificates -- the ones issued to users, services and IoT devices.
    CertificatesApi certificates() const;

    /// Organization CAs and the per-tenant signing CAs chained beneath them.
    CaCertificatesApi ca_certificates() const;

    /// OpenPGP keys used for audit signing and encrypted data export.
    PgpKeysApi pgp_keys() const;

    /// Outbound event notifications. Delivery signatures are verified with the §13 helper,
    /// which this namespace configures.
    WebhooksApi webhooks() const;

    /// Registered OAuth2/OIDC clients -- the registration half of what §12, §21 and §26 then
    /// speak to.
    Oauth2ClientsApi oauth2_clients() const;

    /// Upstream IdP configuration and the per-user links it produces.
    FederationApi federation() const;

    /// Which events raise a notification, and to whom.
    NotificationRulesApi notification_rules() const;

    /// Transactional-mail transport, configurable at organization level and overridable per
    /// tenant.
    EmailConfigApi email_config() const;

    /// Effective settings, and the organization/tenant layers they resolve from.
    SettingsApi settings() const;

    /// Bearer tokens for the SCIM 2.0 provisioning endpoint.
    ScimTokensApi scim_tokens() const;

    /// Registration of §22 AMQP extension actors -- the admin surface §22.9 describes, which no
    /// SDK could previously reach.
    ReactorsApi reactors() const;

    /// Per-tenant attestation policy governing the §24 ceremonies, and the compliance report
    /// over it.
    WebauthnPolicyApi webauthn_policy() const;

    /// Append-only audit log, read-only by construction.
    AuditApi audit() const;

    /// GDPR self-service: the authenticated account's own export and erasure. Scoped to the
    /// caller, never to another user.
    PrivacyApi privacy() const;

    /// Deployment-level probes and FIDO metadata state. Unauthenticated where the server leaves
    /// them so.
    PlatformApi platform() const;

    /// The §27.6 declarative layer: plan and apply a manifest.
    ///
    /// `plan()` writes nothing; `apply()` performs the plan, stops at the first failure and
    /// does not roll back (§27.7).
    ManifestApi manifest() const;

private:
    std::shared_ptr<Transport> transport_;
    CallScope scope_;
};

}  // namespace axiam::management

#endif  // AXIAM_MANAGEMENT_HPP
